#!/bin/sh

## Includes.
. funcrcfileSet

## On exit of the README dialog, if the user chose not to show
## the dialog again then record that in the rcfile.
## On entry: $1 = true to not show again, false to show again

funcDialogReadMeExit() {
	if [ -z "$BASH" ]; then local FUNCNAME=funcDialogReadMeExit; fi
	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME: IN"; fi

	if [ $1 = true ]; then
		funcrcfileSet dialog_readme_show 0 options
	fi

	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME: OUT"; fi
}
