#!/bin/sh

## Get a variable [maintained as a file] from the temporary directory.
## On entry: $1 = name
##  On exit: echoes value

functmpGet() {
	local input

##	if [ -n "$BASH" ]; then		Redundant: fast portable builtin found.
##		echo `<$TEMP_DIR/$1`
##	else
##		cat $TEMP_DIR/$1
##	fi

	read -r input < $TEMP_DIR/$1
	echo $input
}
