#!/bin/sh

## Includes.

## Get a value from the rcfile.
## On entry: $1 = name
##  On exit: echoes value

funcrcfileGet() {
	local value

	value="`grep \"^$1=\" $LOCAL_DATA_DIR/${TARGET}rc`"
	echo ${value#*=}
}
