#!/bin/sh

## Includes.
. functmpSet

## Unschedule a checkbox widget to trigger its default action.
## On entry: $1 = the variable name
##           $2 = the input file name

funcWidgetUnSchedule() {
	if [ -z "$BASH" ]; then local FUNCNAME=funcWidgetUnSchedule; fi
	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME: IN"; fi

	## Local variables.
	local value

	## Indirect referencing (bash uses ${!1} too but it's not portable).
	eval value=\$$1

	if [ $DEBUG_CONTENT -ne 0 ]; then
		echo "$FUNCNAME: $1=$value input-file=$2"
	fi

	## Store the value of the widget.
	functmpSet $2 $value

	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME: OUT"; fi
}
