#!/bin/sh

## Includes.
. funcCoverCreate
. functmpGet

## Set the first file found in the track's folder named cover.* as
## the cover otherwise use the default one.

funcCoverSet() {
	if [ -z "$BASH" ]; then local FUNCNAME=funcCoverSet; fi
	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME: IN"; fi

	## Local variables.
	local playlisttrack="`functmpGet playlisttrack`"
	local trackdir="`dirname "$playlisttrack"`"
	local cover="`ls "$trackdir"/cover.* 2> /dev/null | sed -n '1p'`"

	if [ -z "$cover" ]; then
		cover=$TEMP_DIR/playmusic.svg
		if [ ! -f $cover ]; then
			funcCoverCreate
		fi
	fi
	ln -sf "$cover" $TEMP_DIR/cover

	if [ $DEBUG_CONTENT -ne 0 ]; then echo "$FUNCNAME: cover=$cover"; fi

	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME: OUT"; fi
}
