#line 2 "gtkdialog_lexer.c"

#line 4 "gtkdialog_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer gtkdialog__create_buffer
#define yy_delete_buffer gtkdialog__delete_buffer
#define yy_flex_debug gtkdialog__flex_debug
#define yy_init_buffer gtkdialog__init_buffer
#define yy_flush_buffer gtkdialog__flush_buffer
#define yy_load_buffer_state gtkdialog__load_buffer_state
#define yy_switch_to_buffer gtkdialog__switch_to_buffer
#define yyin gtkdialog_in
#define yyleng gtkdialog_leng
#define yylex gtkdialog_lex
#define yylineno gtkdialog_lineno
#define yyout gtkdialog_out
#define yyrestart gtkdialog_restart
#define yytext gtkdialog_text
#define yywrap gtkdialog_wrap
#define yyalloc gtkdialog_alloc
#define yyrealloc gtkdialog_realloc
#define yyfree gtkdialog_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE gtkdialog_restart(gtkdialog_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int gtkdialog_leng;

extern FILE *gtkdialog_in, *gtkdialog_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gtkdialog_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up gtkdialog_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via gtkdialog_restart()), so that the user can continue scanning by
	 * just pointing gtkdialog_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when gtkdialog_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int gtkdialog_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow gtkdialog_wrap()'s to do buffer switches
 * instead of setting up a fresh gtkdialog_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void gtkdialog_restart (FILE *input_file  );
void gtkdialog__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE gtkdialog__create_buffer (FILE *file,int size  );
void gtkdialog__delete_buffer (YY_BUFFER_STATE b  );
void gtkdialog__flush_buffer (YY_BUFFER_STATE b  );
void gtkdialog_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void gtkdialog_pop_buffer_state (void );

static void gtkdialog_ensure_buffer_stack (void );
static void gtkdialog__load_buffer_state (void );
static void gtkdialog__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER gtkdialog__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE gtkdialog__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE gtkdialog__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE gtkdialog__scan_bytes (yyconst char *bytes,int len  );

void *gtkdialog_alloc (yy_size_t  );
void *gtkdialog_realloc (void *,yy_size_t  );
void gtkdialog_free (void *  );

#define yy_new_buffer gtkdialog__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        gtkdialog_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        gtkdialog_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *gtkdialog_in = (FILE *) 0, *gtkdialog_out = (FILE *) 0;

typedef int yy_state_type;

extern int gtkdialog_lineno;

int gtkdialog_lineno = 1;

extern char *gtkdialog_text;
#define yytext_ptr gtkdialog_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up gtkdialog_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	gtkdialog_leng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 138
#define YY_END_OF_BUFFER 139
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[361] =
    {   0,
      139,  130,  137,  138,  136,  137,  138,  135,  138,  126,
      137,  138,    2,  130,  137,  138,  137,  138,    1,  137,
      138,  137,  138,   17,  137,  138,    2,  137,  138,   14,
      137,  138,   16,  137,  138,   14,   15,  137,  138,   15,
      137,  138,    6,  137,  138,    3,  137,  138,    4,  137,
      138,    5,  137,  138,    7,  137,  138,    7,  136,  137,
      138,    7,  135,  138,    9,  137,  138,    2,    7,  137,
      138,  137,  138,  131,  137,  138,  131,  136,  137,  138,
        2,  131,  137,  138,  134,  137,  138,  137,  138,  127,
      137,  138,  127,  136,  137,  138,  127,  135,  138,  129,

      137,  138,    2,  127,  137,  138,  137,  138,  130,    2,
      130,    2,  125,   16,   15,    3,    7,    2,    7,    8,
      131,    2,  131,  133,  132,  133,  127,    2,  127,  128,
      124,  125,   19,  124,  125,   46,   45,  125,   73,  125,
       31,   30,  125,  102,  100,  125,   79,   78,  125,   85,
      125,   37,   36,  125,   49,   48,  125,   28,   27,  125,
       47,  124,  125,   74,  124,  125,   32,  124,  125,  101,
      124,  125,   80,  124,  125,   86,  124,  125,   38,  124,
      125,   50,  124,  125,   29,  124,  125,   44,   42,  125,
       33,  125,  117,  113,  125,   98,  125,   71,  125,   10,

      125,   81,  125,  111,  125,   43,  124,  125,   35,  124,
      125,  114,  124,  125,   99,  124,  125,   72,  124,  125,
       82,  124,  125,   20,  124,  125,  112,  124,  125,  122,
      121,  125,16440,   54,  125,  109,  125,  117,  118,  125,
       41,   39,  125,   22,   21,  125,  123,  124,  125,   55,
      124,  125,  110,  124,  125,  119,  124,  125,   40,  124,
      125,   23,  124,  125,16440, 8248,   53,   51,  125,  103,
      125,   34,   83,  125,  105,  125,   52,  124,  125,   18,
      124,  125,  104,  124,  125,   84,  124,  125,  106,  124,
      125,   64,   62,  125,   76,   75,  125,   88,   87,  125,

       26,   24,  125,  107,  125,   63,  124,  125,   77,  124,
      125,   89,  124,  125,   25,  124,  125,  108,  124,  125,
       61,   57,   90,  125,   91,  124,  125,   60,   94,   92,
      125,  116,  115,   97,   95,  125,   93,  124,  125,   96,
      124,  125,   59,  120,   70,   68,  125,   67,   65,  125,
       69,  124,  125,   66,  124,  125,   58,   12,   13,   11
    } ;

static yyconst flex_int16_t yy_accept[670] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    5,    8,   10,   13,   17,   19,
       22,   24,   27,   30,   33,   36,   40,   43,   46,   49,
       52,   55,   58,   62,   65,   68,   72,   74,   77,   81,
       85,   88,   90,   93,   97,  100,  103,  107,  109,  110,
      112,  113,  113,  113,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  115,  116,  117,  118,  120,  121,
      122,  124,  125,  127,  128,  130,  131,  131,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,

      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  137,  139,  139,  139,  141,
      142,  144,  144,  144,  144,  144,  145,  147,  147,  148,
      150,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  153,  155,  156,  158,  158,  159,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  164,  164,  164,  167,  170,  170,  170,  170,  173,
      173,  176,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  182,  185,  185,  188,  188,  188,  188,  188,

      188,  188,  188,  188,  188,  188,  188,  188,  189,  191,
      191,  193,  193,  193,  193,  194,  196,  198,  198,  198,
      198,  198,  198,  198,  200,  200,  200,  202,  204,  204,
      204,  204,  204,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  209,  212,  212,  212,  215,  218,  218,  218,
      218,  218,  218,  218,  221,  221,  221,  224,  224,  224,
      224,  227,  230,  230,  231,  233,  234,  236,  236,  236,
      236,  236,  236,  236,  238,  238,  238,  239,  239,  239,
      239,  239,  239,  241,  242,  244,  244,  244,  244,  244,
      244,  244,  244,  245,  247,  250,  253,  253,  253,  253,

      253,  253,  256,  256,  256,  256,  256,  259,  262,  262,
      262,  262,  262,  262,  262,  265,  266,  266,  267,  267,
      267,  267,  267,  267,  267,  268,  270,  270,  270,  272,
      273,  273,  273,  273,  275,  275,  275,  275,  275,  275,
      275,  275,  277,  277,  277,  277,  280,  280,  283,  286,
      286,  289,  289,  289,  289,  289,  289,  289,  292,  292,
      292,  292,  292,  292,  292,  293,  295,  296,  298,  298,
      298,  298,  298,  299,  301,  302,  304,  304,  304,  304,
      304,  306,  306,  306,  309,  312,  312,  315,  318,  318,
      318,  318,  321,  321,  321,  321,  322,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  325,  325,  325,  325,
      325,  325,  328,  328,  328,  328,  329,  329,  330,  332,
      332,  333,  334,  334,  334,  334,  335,  337,  337,  340,
      340,  340,  343,  343,  344,  344,  344,  345,  346,  348,
      349,  351,  351,  354,  357,  357,  357,  357,  357,  357,
      358,  358,  358,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  360,  360,  360,  360,  360,  361,  361
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    1,    1,    1,
        1,    7,    7,    8,    9,    8,   10,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    7,    1,   11,
       12,   13,    1,    1,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
        1,   15,    1,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   14,   26,   27,   28,   29,
       30,   31,   14,   32,   33,   34,   35,   36,   37,   38,
       39,   14,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    5,    1,
        6,    7,    8,    5,    9,   10,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[685] =
    {   0,
        0,   12,   25,   41,   57,   72,   86,  100,  114,  128,
      142,  156, 1171,    0, 1172, 1172, 1172,    5,  171, 1172,
     1172, 1172,   17, 1172, 1162,    0,    0, 1172,    0, 1172,
     1172,    0,    0,    0, 1172,   91, 1164,    0,    0,   94,
     1172, 1157,    0,    0,    0, 1172,  105, 1162,    0,  108,
      119, 1153,  210, 1172,  100,  101,  111,  129,  120,   68,
      115,  237,  141,  139,  238,    9,  239,  240,  152,  243,
      256,  258,  113, 1157,    0,    0,    0,  164, 1172,    0,
      258, 1172, 1172,    0,  276, 1172,  275, 1172, 1145, 1128,
      233, 1141,  261, 1129, 1124,  268,  288,  296, 1138, 1128,

     1122,  291, 1139, 1134,  297,  302,  260,  253,  302,  311,
       58,  312,  313,  315,  320,  317,  318,  326,  331,  341,
      327,  334,  343,  330,  333,  337,  340,  344,  346,  347,
      352,  351,  355,  353,  356,  357,  362,  365,  359,  371,
      366, 1120, 1119,  364, 1124, 1129, 1125, 1115, 1131, 1122,
     1116, 1120, 1123, 1130, 1111, 1120, 1122, 1106, 1109, 1103,
     1102, 1097, 1104, 1113, 1101, 1113, 1092, 1108, 1096, 1097,
     1093, 1104, 1099,  368,  374,  377,  387,  380,  389,  388,
      390,  391,  399,  400,  395,  396,  401,  411,  403,  407,
      405,  408,  409,  416,  412,  418,  426,  423,  428,  421,

      241,  427,  434,  437,  438,  439,  440,  441,  443,  446,
     1098, 1088, 1102, 1090,  439, 1102, 1084, 1085, 1088, 1087,
     1076, 1090, 1081, 1172, 1076, 1082, 1088, 1074, 1072, 1085,
     1074, 1076, 1080, 1077, 1084, 1073, 1065, 1077, 1072, 1058,
     1070, 1063, 1066, 1058, 1071,  450,  452,  447,  456,  457,
      461,  459,  471,  114,  470, 1077,  475,   42,  468, 1059,
      473,  486,  479,  489,  483,  482,  484,  492,  485,  490,
      491,  500,  501,  508,  511,  512,  514,  498,  513,  515,
      518,  519, 1058, 1057, 1060, 1052, 1054, 1066, 1047, 1068,
     1041, 1058, 1065, 1064, 1052, 1058, 1040, 1060, 1045, 1058,

      520, 1052, 1034, 1051, 1035, 1036, 1033, 1043, 1050, 1049,
     1044, 1047, 1041, 1041, 1036, 1032, 1025,  521,  522,  526,
      527,  528,  524,  530, 1050, 1172,  543,  548, 1172, 1049,
     1172,  541,  542, 1023,  554, 1047, 1172, 1037, 1045, 1172,
     1172,  546,  547,  549,  551,  552,  555,  553,  556, 1035,
     1034, 1042, 1172, 1041, 1172,  559, 1040, 1172,  557,  565,
      576, 1030,  569, 1013, 1012, 1022, 1018, 1020, 1008, 1009,
     1172, 1022, 1021, 1172, 1172,  999, 1000, 1018, 1172, 1017,
     1172, 1172, 1012,  994,  997,  992,  994, 1003,  573, 1006,
     1009, 1172, 1172, 1003, 1172,  993,  987, 1005, 1004,  979,

      583,  586,  575,  579,  580,  581,  582, 1011, 1172,    0,
     1172, 1001,  585,  993,  596, 1172, 1172,  590,  591,  594,
      604,  610,  596, 1172,  600,  602, 1172, 1172,  606,  607,
      608,  622, 1172,  626,  999,  998,  980,  977,  978,  987,
      972, 1172, 1172,  992,  987, 1172, 1172,  971,  981,  971,
      987,  986,  965, 1172,  962,  962, 1172,  968,  973,  976,
     1172, 1172,  979,  987, 1172,  638, 1172,  614,  627,  621,
      633,  977,  976, 1172,  619,  963,  983,  961,  972,  630,
      625,  962, 1172,  979, 1172,  631,  632,  635,  634,  969,
      636,  951,  976, 1172, 1172, 1172,  941,  965,  939,  963,

      962, 1172,  940,  960,  944,  945, 1172, 1172,  937,  935,
      938,  946,  953,  931, 1172,  657,  659, 1172,  668,  669,
      670,  671,  672,  674,  960, 1172,  675,  682, 1172, 1172,
      676,  929,  935, 1172,  688,  690,  936,  678,  682,  685,
      947, 1172,  689,  930,  945, 1172,  944, 1172, 1172,  926,
     1172,  942,  941,  935,  918,  919,  937, 1172,  919,  700,
      701,  710,  714,  703,  944, 1172,  943, 1172,  913,  698,
      920,  923,  939, 1172,  938, 1172,  914,  643,  695,  927,
     1172,  707,  919, 1172, 1172,  906, 1172, 1172,  919,  905,
      920, 1172,  899,  728,  729, 1172, 1172,  730,  894,  731,

      882,  733,  887,  718,  725, 1172,  744,  878,  878,  856,
      856, 1172,  868,  741,  751, 1172,  853,  869, 1172,  839,
      863, 1172,  853,  745,  748,  861, 1172,  828, 1172,  846,
      842, 1172,  747, 1172,  769,  761, 1172,  764, 1172,  762,
     1172,  731, 1172, 1172,  763,  695,  765,  705,  691, 1172,
      626,  766, 1172,  253,  193,  768,  126,  774,  777,   65,
      779, 1172,  775,  781,  784,  786, 1172, 1172,  793,  803,
      813,  823,  833,  843,  853,    5,  859,  869,  879,  889,
      899,  909,  919,  927
    } ;

static yyconst flex_int16_t yy_def[685] =
    {   0,
      669,  669,  670,  670,  671,  671,  672,  672,  673,  673,
      674,  674,  668,  675,  668,  668,  668,  675,  668,  668,
      668,  668,  668,  668,  668,  676,  676,  668,  677,  668,
      668,  678,  678,  678,  668,  678,  668,  679,  679,  679,
      668,  680,  681,  681,  681,  668,  681,  668,  675,  675,
      668,  682,  668,  668,  682,  682,  682,  682,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,
      682,  682,  682,  668,  676,  677,  678,  678,  668,  679,
      679,  668,  668,  681,  681,  668,   53,  668,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       87,   87,   87,   87,   87,   87,   87,  682,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,
      682,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,  682,  682,  682,  682,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  668,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,

      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,  668,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,  682,  682,  682,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  668,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,
      682,  682,  682,  682,  682,  682,  682,  682,  682,  682,
      682,  682,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,  682,  682,  682,
      682,  682,  682,  682,  668,  668,  682,  682,  668,  668,
      668,  682,  682,  668,  682,  668,  668,  682,  668,  668,
      668,  682,  682,  682,  682,  682,  682,  682,  682,  682,
      682,  668,  668,  668,  668,  682,  668,  668,  682,  682,
      682,  682,  682,   87,   87,   87,   87,   87,   87,   87,
      668,   87,   87,  668,  668,   87,   87,   87,  668,   87,
      668,  668,   87,   87,   87,   87,   87,   87,   87,   87,
       87,  668,  668,   87,  668,   87,   87,   87,   87,   87,

      682,  682,  682,  682,  682,  682,  682,  668,  668,  683,
      668,  682,  682,  668,  668,  668,  668,  682,  682,  682,
      682,  682,  682,  668,  682,  682,  668,  668,  682,  682,
      682,  668,  668,  682,   87,   87,   87,   87,   87,   87,
       87,  668,  668,   87,   87,  668,  668,   87,   87,   87,
       87,   87,   87,  668,   87,   87,  668,   87,   87,   87,
      668,  668,   87,  668,  668,  684,  668,  682,  682,  682,
      682,  682,  683,  668,  682,  668,  668,  668,  682,  682,
      682,  668,  668,  668,  668,  682,  682,  682,  682,  682,
      682,  668,  668,  668,  668,  668,   87,   87,   87,   87,

       87,  668,   87,   87,   87,   87,  668,  668,   87,   87,
       87,   87,   87,   87,  668,  684,  684,  668,  684,  684,
      684,  684,  684,  682,  668,  668,  682,  668,  668,  668,
      682,  668,  668,  668,  682,  682,  668,  682,  682,  682,
      682,  668,  682,  668,   87,  668,   87,  668,  668,   87,
      668,   87,   87,   87,   87,   87,   87,  668,   87,  684,
      684,  684,  684,  684,  668,  668,  668,  668,  668,  682,
      668,  668,  668,  668,  668,  668,  668,  682,  682,  682,
      668,  682,  668,  668,  668,   87,  668,  668,   87,   87,
       87,  668,   87,  684,  684,  668,  668,  684,  668,  682,

      668,  668,  668,  682,  682,  668,  682,  668,   87,   87,
       87,  668,   87,  684,  684,  668,  668,  668,  668,  668,
      668,  668,  668,  682,  682,  668,  668,  668,  668,   87,
       87,  668,  684,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  684,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,    0,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668
    } ;

static yyconst flex_int16_t yy_nxt[1212] =
    {   0,
      668,   15,   16,   15,   17,   18,   50,   51,   50,   75,
       19,  668,   20,   15,   16,   15,   17,   18,   51,   51,
       51,   54,   19,  668,   20,   21,   15,   16,   15,   22,
       23,   24,   25,   26,   24,   24,   24,   24,  126,   21,
       21,   21,   15,   16,   15,   22,   23,   24,   25,   26,
       24,   24,   24,   24,   54,   21,   21,   21,   15,   16,
       15,   28,   23,   21,   21,  332,   21,   21,   30,   31,
       54,   21,   21,   15,   16,   15,   28,   23,   21,   21,
       54,   21,   21,   30,   31,  179,   21,   33,   34,   33,
       35,   36,   78,   78,   78,   81,   51,   81,  663,  115,

       37,   33,   34,   33,   35,   36,   85,   85,   85,   50,
       51,   50,   54,   54,   37,   39,   16,   39,  108,   40,
       51,   51,   51,   54,   41,   54,   54,   54,   42,   39,
       16,   39,   54,   40,  110,  109,  140,  141,   41,  113,
      111,   54,   42,   44,   45,   44,   46,   47,  114,  112,
      116,   54,  327,   54,  660,  123,   48,   44,   45,   44,
       46,   47,  120,  124,   54,   78,   78,   78,  130,  121,
       48,   52,   52,   52,  122,   52,   52,   52,   52,   52,
       53,   52,   52,   54,   52,   52,   52,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   52,   64,   65,   66,

       67,   68,   69,   70,   71,   52,   72,   73,   52,   52,
       87,   87,   87,  657,   87,   87,   87,   87,   87,   87,
       87,   87,   88,   87,   87,   87,   89,   90,   91,   92,
       93,   94,   95,   96,   97,   87,   98,   99,  100,  101,
      102,  103,  104,  105,   87,  106,  107,   87,   87,   54,
       54,   54,   54,   54,  117,   54,  144,  118,  125,   81,
       51,   81,  145,  131,  128,   54,  132,  273,   54,  119,
       54,  129,  133,  127,  136,  137,  134,   85,   85,   85,
      147,  656,  138,  173,  174,  151,  175,  135,  152,  148,
      139,   87,   87,   87,   87,   87,   87,   87,   87,   87,

      153,   87,   87,   87,   87,   87,   87,   87,   87,  154,
       87,   87,  157,  166,   54,  162,  155,  167,  169,  170,
      158,  156,  163,   54,   54,   54,  171,   54,  168,   54,
       54,  177,   54,  180,  172,  176,  183,  181,   54,   54,
      178,  184,   54,   54,  188,   54,   54,  185,  182,   54,
      186,  187,   54,   54,  190,   54,   54,  189,   54,   54,
      191,  193,  192,   54,   54,   54,  198,   54,   54,   54,
      194,   54,  201,  195,   54,  197,  203,   54,   54,  207,
      200,  196,  199,   54,  213,  209,   54,  244,  204,   54,
      202,  205,   54,  214,  210,  208,  245,  206,  246,   54,

       54,   54,   54,   54,  252,  248,  250,   54,   54,  249,
      247,   54,   54,   54,  188,   54,  251,   54,  258,   54,
       54,   54,  254,  253,   54,  263,  255,  256,   54,  260,
       54,  259,  257,   54,  262,   54,  266,  261,   54,   54,
       54,  264,  267,  265,  271,  268,   54,  270,  269,   54,
       54,   54,   54,   54,  275,   54,  287,  272,   54,   54,
      274,  276,   54,  278,   54,  282,  288,  280,   54,   54,
      279,   54,  320,   54,  325,  277,  281,  323,  330,  318,
       54,  319,   54,  326,  333,   54,  322,  331,  321,  336,
      328,   54,  339,  324,   54,  341,   54,   54,  337,  344,

      342,  340,   54,   54,   54,  338,  335,  343,  346,  350,
       54,  352,   54,   54,  354,  359,  347,  357,  345,  348,
      353,  351,  349,  355,   54,   54,  358,   54,  356,  360,
       54,   54,  382,   54,   54,  361,   54,  383,   54,   54,
       54,  362,   54,  403,  384,  405,  408,  404,  363,  401,
      402,  410,  406,   54,   54,  409,  407,  415,   54,   54,
      411,   54,  418,   54,   54,  424,  416,   54,   54,   54,
      425,   54,  426,  413,  412,  423,  429,   54,  420,  432,
      419,   54,  422,  430,  421,  454,  464,   54,   54,  466,
      455,   54,   54,   54,   54,  465,  431,   54,  467,  477,

      471,  475,   54,   54,  468,  434,   54,  482,   54,  470,
      469,  480,   54,  484,   54,  472,  483,  478,   54,   54,
       54,  479,  485,  481,  491,  432,   54,  490,  486,  493,
      525,   54,  489,   54,  487,  488,  528,   54,  494,  526,
      492,  516,   54,   54,   54,   54,   54,   54,   54,  518,
      536,  524,  531,  655,  541,   54,  519,  535,  527,  604,
      516,  520,  668,  538,  540,  539,  521,  522,  518,  543,
      518,  668,  668,  668,  668,  668,  523,  565,  567,  518,
      518,  518,  518,  518,  560,  528,  566,  568,   54,  561,
       54,  573,  564,  575,   54,  578,  563,   54,  569,  562,

      574,   54,  576,  668,  668,  570,  668,   54,  652,  653,
       54,  518,  518,  668,  518,  579,  580,  668,  582,   54,
      654,  518,  596,  651,  605,  518,  597,  595,  594,  600,
       54,  668,  668,  668,  618,  598,  621,   54,  607,  518,
      518,  518,  616,  619,  668,  622,  614,  626,  638,  624,
      668,  640,  518,  625,  668,  649,  627,  639,  518,  615,
      641,  633,  518,  634,  647,  640,  668,  638,  647,  652,
      653,  658,  648,  645,  518,  650,  648,  658,  664,  659,
      661,  662,  661,  662,  664,  659,  665,  666,  667,  666,
      667,  646,  665,   14,   14,   14,   14,   14,   14,   14,

       14,   14,   14,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   49,  644,   49,   49,   49,  643,   49,
       49,  642,   49,   76,  626,  637,  621,  636,   76,   77,
       77,   77,  618,   77,   77,   77,   77,  635,   77,   80,
      632,   80,   80,   80,  631,   80,   80,  630,   80,   82,
      629,   82,   82,   82,   82,   82,   82,   82,   82,   84,

       84,   84,  628,   84,   84,   84,   84,  623,   84,   52,
       52,  620,   52,   52,   52,   52,   52,   52,   52,  473,
      473,  473,  473,  473,  473,  473,  617,  473,  473,  517,
      613,  517,  612,  517,  611,  610,  517,  609,  608,  606,
      603,  575,  573,  602,  601,  599,  567,  565,  593,  592,
      591,  590,  589,  588,  587,  586,  585,  584,  583,  581,
      577,  572,  571,  525,  559,  558,  557,  556,  555,  554,
      553,  552,  551,  550,  549,  548,  547,  546,  545,  493,
      544,  542,  484,  537,  534,  533,  477,  532,  530,  529,
      464,  515,  514,  513,  512,  511,  510,  509,  508,  507,

      506,  505,  504,  503,  502,  501,  500,  499,  498,  497,
      496,  495,  476,  474,  408,  463,  462,  461,  460,  459,
      458,  457,  456,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  433,  357,  354,  352,  428,  427,  339,  417,
      336,  414,  330,  325,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  334,  329,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,

      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  286,
      285,  284,  283,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  212,  211,  165,  164,  161,  160,  159,  150,
      149,  146,  143,  142,   74,   54,   86,   83,   79,   74,
      668,   13,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,

      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668
    } ;

static yyconst flex_int16_t yy_chk[1212] =
    {   0,
        0,    1,    1,    1,    1,    1,   18,   18,   18,  676,
        1,    0,    1,    2,    2,    2,    2,    2,   23,   23,
       23,   66,    2,    0,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   66,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,  258,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,  258,    5,    5,    5,    5,
      111,    5,    6,    6,    6,    6,    6,    6,    6,    6,
       60,    6,    6,    6,    6,  111,    6,    7,    7,    7,
        7,    7,   36,   36,   36,   40,   40,   40,  660,   60,

        7,    8,    8,    8,    8,    8,   47,   47,   47,   50,
       50,   50,   55,   56,    8,    9,    9,    9,   55,    9,
       51,   51,   51,   57,    9,   73,  254,   61,    9,   10,
       10,   10,   59,   10,   57,   56,   73,   73,   10,   59,
       57,   58,   10,   11,   11,   11,   11,   11,   59,   58,
       61,   64,  254,   63,  657,   64,   11,   12,   12,   12,
       12,   12,   63,   64,   69,   78,   78,   78,   69,   63,
       12,   19,   19,   19,   63,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       53,   53,   53,  655,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   62,
       65,   67,   68,  201,   62,   70,   91,   62,   65,   81,
       81,   81,   91,   70,   68,  108,   70,  201,   71,   62,
       72,   68,   71,   67,   72,   72,   71,   85,   85,   85,
       93,  654,   72,  107,  107,   96,  108,   71,   96,   93,
       72,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       96,   87,   87,   87,   87,   87,   87,   87,   87,   97,
       87,   87,   98,  105,  109,  102,   97,  105,  106,  106,
       98,   97,  102,  110,  112,  113,  106,  114,  105,  116,
      117,  110,  115,  112,  106,  109,  115,  113,  118,  121,
      110,  116,  124,  119,  120,  125,  122,  117,  114,  126,
      118,  119,  127,  120,  122,  123,  128,  121,  129,  130,
      123,  125,  124,  132,  131,  134,  130,  133,  135,  136,
      126,  139,  133,  127,  137,  129,  135,  138,  141,  139,
      132,  128,  131,  140,  144,  141,  175,  174,  136,  176,
      134,  137,  178,  144,  141,  140,  174,  138,  175,  177,

      180,  179,  181,  182,  180,  177,  179,  185,  186,  178,
      176,  183,  184,  187,  188,  189,  179,  191,  186,  190,
      192,  193,  182,  181,  195,  191,  183,  184,  194,  188,
      196,  187,  185,  200,  190,  198,  194,  189,  197,  202,
      199,  192,  195,  193,  199,  196,  203,  198,  197,  204,
      205,  206,  207,  208,  203,  209,  215,  200,  210,  248,
      202,  204,  246,  206,  247,  210,  215,  208,  249,  250,
      207,  252,  248,  251,  253,  205,  209,  251,  257,  246,
      259,  247,  255,  253,  259,  261,  250,  257,  249,  262,
      255,  263,  264,  252,  266,  265,  267,  269,  262,  266,

      265,  264,  270,  271,  268,  263,  261,  265,  268,  272,
      278,  274,  272,  273,  275,  278,  269,  277,  267,  270,
      274,  273,  271,  275,  276,  279,  277,  280,  276,  279,
      281,  282,  301,  318,  319,  280,  323,  301,  320,  321,
      322,  281,  324,  320,  301,  322,  327,  321,  282,  318,
      319,  328,  323,  332,  333,  327,  324,  335,  342,  343,
      328,  344,  342,  345,  346,  348,  335,  347,  349,  359,
      348,  356,  349,  333,  332,  347,  356,  360,  344,  361,
      343,  363,  346,  359,  345,  389,  401,  403,  361,  402,
      389,  404,  405,  406,  407,  401,  360,  413,  402,  415,

      406,  413,  418,  419,  403,  363,  420,  421,  423,  405,
      404,  419,  425,  422,  426,  407,  421,  415,  429,  430,
      431,  418,  422,  420,  431,  432,  468,  430,  423,  434,
      469,  475,  429,  470,  425,  426,  471,  481,  434,  469,
      432,  466,  480,  486,  487,  471,  489,  488,  491,  466,
      481,  468,  475,  651,  489,  578,  466,  480,  470,  578,
      516,  466,  517,  486,  488,  487,  466,  466,  516,  491,
      517,  519,  520,  521,  522,  523,  466,  524,  527,  519,
      520,  521,  522,  523,  519,  528,  524,  527,  531,  520,
      538,  535,  523,  536,  539,  538,  522,  540,  528,  521,

      535,  543,  536,  560,  561,  531,  564,  579,  648,  648,
      570,  560,  561,  562,  564,  539,  540,  563,  543,  582,
      649,  562,  562,  646,  579,  563,  563,  561,  560,  570,
      604,  594,  595,  598,  600,  564,  602,  605,  582,  594,
      595,  598,  598,  600,  614,  602,  594,  607,  624,  604,
      633,  625,  614,  605,  615,  642,  607,  624,  633,  595,
      625,  614,  615,  615,  636,  640,  645,  638,  647,  652,
      652,  656,  636,  633,  645,  645,  647,  658,  663,  656,
      659,  659,  661,  661,  664,  658,  663,  665,  665,  666,
      666,  635,  664,  669,  669,  669,  669,  669,  669,  669,

      669,  669,  669,  670,  670,  670,  670,  670,  670,  670,
      670,  670,  670,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  673,  673,  673,  673,  673,  673,  673,
      673,  673,  673,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  675,  631,  675,  675,  675,  630,  675,
      675,  628,  675,  677,  626,  623,  621,  620,  677,  678,
      678,  678,  618,  678,  678,  678,  678,  617,  678,  679,
      613,  679,  679,  679,  611,  679,  679,  610,  679,  680,
      609,  680,  680,  680,  680,  680,  680,  680,  680,  681,

      681,  681,  608,  681,  681,  681,  681,  603,  681,  682,
      682,  601,  682,  682,  682,  682,  682,  682,  682,  683,
      683,  683,  683,  683,  683,  683,  599,  683,  683,  684,
      593,  684,  591,  684,  590,  589,  684,  586,  583,  580,
      577,  575,  573,  572,  571,  569,  567,  565,  559,  557,
      556,  555,  554,  553,  552,  550,  547,  545,  544,  541,
      537,  533,  532,  525,  514,  513,  512,  511,  510,  509,
      506,  505,  504,  503,  501,  500,  499,  498,  497,  493,
      492,  490,  484,  482,  479,  478,  477,  476,  473,  472,
      464,  463,  460,  459,  458,  456,  455,  453,  452,  451,

      450,  449,  448,  445,  444,  441,  440,  439,  438,  437,
      436,  435,  414,  412,  408,  400,  399,  398,  397,  396,
      394,  391,  390,  388,  387,  386,  385,  384,  383,  380,
      378,  377,  376,  373,  372,  370,  369,  368,  367,  366,
      365,  364,  362,  357,  354,  352,  351,  350,  339,  338,
      336,  334,  330,  325,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  260,  256,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,

      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  223,  222,  221,  220,  219,  218,  217,  216,  214,
      213,  212,  211,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  143,  142,  104,  103,  101,  100,   99,   95,
       94,   92,   90,   89,   74,   52,   48,   42,   37,   25,
       13,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,

      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668
    } ;

extern int gtkdialog__flex_debug;
int gtkdialog__flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up gtkdialog_text */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *gtkdialog_text;
#line 1 "gtkdialog_lexer.l"
#line 2 "gtkdialog_lexer.l"
/*
** $Id: lexer.l,v 1.2 2004/11/20 20:01:25 root Exp root $
** $Log: lexer.l,v $
** Revision 1.2  2004/11/20 20:01:25  root
** - Log entries.
**
*/
#define YY_INPUT(buf,result,max_size) \
    { \
    int c = getnextchar(); \
    result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
    }


#include <string.h>
#include <gtk/gtk.h>

#include "gtkdialog.h"
#include "attributes.h"
#include "gtkdialog_parser.h"

static gchar *process_string(gchar *str);

extern int linenumber;
gchar *Token;




#line 1055 "gtkdialog_lexer.c"

#define INITIAL 0
#define EMBEDDED 1
#define ST_TAG_ATTR 2
#define ST_QUOTED_TAGATTR 3
#define ST_STRING 4
#define ST_QUOTED_STRING 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int gtkdialog_lex_destroy (void );

int gtkdialog_get_debug (void );

void gtkdialog_set_debug (int debug_flag  );

YY_EXTRA_TYPE gtkdialog_get_extra (void );

void gtkdialog_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *gtkdialog_get_in (void );

void gtkdialog_set_in  (FILE * in_str  );

FILE *gtkdialog_get_out (void );

void gtkdialog_set_out  (FILE * out_str  );

int gtkdialog_get_leng (void );

char *gtkdialog_get_text (void );

int gtkdialog_get_lineno (void );

void gtkdialog_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int gtkdialog_wrap (void );
#else
extern int gtkdialog_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( gtkdialog_text, gtkdialog_leng, 1, gtkdialog_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( gtkdialog_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( gtkdialog_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, gtkdialog_in))==0 && ferror(gtkdialog_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(gtkdialog_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int gtkdialog_lex (void);

#define YY_DECL int gtkdialog_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after gtkdialog_text and gtkdialog_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 34 "gtkdialog_lexer.l"


	#ifdef DEBUG
		g_message("%s(): Start", __func__);
	#endif

#line 1254 "gtkdialog_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)gtkdialog_alloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in gtkdialog_lex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! gtkdialog_in )
			gtkdialog_in = stdin;

		if ( ! gtkdialog_out )
			gtkdialog_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			gtkdialog_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE );
		}

		gtkdialog__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of gtkdialog_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 669 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1172 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 40 "gtkdialog_lexer.l"
{ Token=">"; return(gtkdialog_text[0]); 			}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "gtkdialog_lexer.l"
{ Token="indent chars"; 				}
	YY_BREAK
/*
	 * Attributes.
	 */
case 3:
YY_RULE_SETUP
#line 46 "gtkdialog_lexer.l"
{
	#ifdef DEBUG 
	g_message(" -> TAG_ATTR_NAME: '%s'", gtkdialog_text);
	#endif
	Token="tag attribute name";
	gtkdialog_lval.cval=strdup(gtkdialog_text);
	return TAG_ATTR_NAME;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "gtkdialog_lexer.l"
{
					  #ifdef DEBUG 
					  g_message(" -> spec char: '%s'", gtkdialog_text);
					  #endif
					  Token="=";
					  return '=';
												}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "gtkdialog_lexer.l"
{
					  #ifdef DEBUG 
					  g_message(" -> spec char: '%s'", gtkdialog_text);
					  #endif
					  Token=">";
					  BEGIN(0);
					  return '>';
												}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "gtkdialog_lexer.l"
{
					  Token = "double quote";
					  BEGIN(ST_QUOTED_TAGATTR);				}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 76 "gtkdialog_lexer.l"
{
					  Token = "string";
					  yymore();						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "gtkdialog_lexer.l"
{
					  Token = "string";
					  yymore();						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "gtkdialog_lexer.l"
{
					  Token = gtkdialog_text;
					  gtkdialog_lval.cval = g_strdup(gtkdialog_text);
					  gtkdialog_lval.cval[strlen(gtkdialog_lval.cval) - 1] = '\0';
					  BEGIN(ST_TAG_ATTR);
					  return STRING;
					  							}
	YY_BREAK
/*
	 * The elements of the embedded imperative language.
	 */
case 10:
YY_RULE_SETUP
#line 100 "gtkdialog_lexer.l"
{ 
	Token="<show/>"; 
	return SHOW_WIDGETS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 105 "gtkdialog_lexer.l"
{
	Token="<command>";    
	BEGIN(EMBEDDED);
	return COMM;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "gtkdialog_lexer.l"
{
	Token="<if>";    
	BEGIN(EMBEDDED);
	return IF;           
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 117 "gtkdialog_lexer.l"
{
	Token="<while>";    
	BEGIN(EMBEDDED);
	return WHILE;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 123 "gtkdialog_lexer.l"
{
	Token = "operator";
	return gtkdialog_text[0];
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 128 "gtkdialog_lexer.l"
{
	Token = "variable";
	gtkdialog_lval.cval = g_strdup(gtkdialog_text);
	return EMB_VARIABLE;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "gtkdialog_lexer.l"
{
	Token = "number";
	gtkdialog_lval.cval = g_strdup(gtkdialog_text);
	return EMB_NUMBER;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 140 "gtkdialog_lexer.l"
{ 
	BEGIN(0);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 144 "gtkdialog_lexer.l"
{ 
	Token="</if>"; 
	return ENDCOMM;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 149 "gtkdialog_lexer.l"
{ 
	Token="</if>"; 
	return ENDIF;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 154 "gtkdialog_lexer.l"
{ 
	Token="</while>"; 
	return EWHILE;
}
	YY_BREAK
/*
	 * The widget tags.
	 */
case 21:
YY_RULE_SETUP
#line 163 "gtkdialog_lexer.l"
{ 
	Token="<window>"; 
	return(WINDOW);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "gtkdialog_lexer.l"
{ 
	Token="<window>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_WINDOW);  		
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 174 "gtkdialog_lexer.l"
{ 
	Token="</window>"; 
	return(EWINDOW);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 180 "gtkdialog_lexer.l"
{ 
	Token="<notebook>"; 
	return(NOTEBOOK);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 185 "gtkdialog_lexer.l"
{ 
	Token="</notebook>"; 
	return(ENOTEBOOK);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 190 "gtkdialog_lexer.l"
{ 
	Token="<notebook>";
	BEGIN(ST_TAG_ATTR);
	return(PART_NOTEBOOK);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 197 "gtkdialog_lexer.l"
{ 
	Token="<vbox>"; 
	return(VBOX);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 202 "gtkdialog_lexer.l"
{ 
	Token="<hbox>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_VBOX);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 208 "gtkdialog_lexer.l"
{ 
	Token="</vbox>"; 
	return(EVBOX);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 214 "gtkdialog_lexer.l"
{ 
	Token="<hbox>"; 
	return(HBOX);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 219 "gtkdialog_lexer.l"
{ 
	Token="<hbox>";
	BEGIN(ST_TAG_ATTR);
	return(PART_HBOX);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 225 "gtkdialog_lexer.l"
{ 
	Token="</hbox>"; 
	return(EHBOX);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 231 "gtkdialog_lexer.l"
{ 
	Token="<frame>"; 
	gtkdialog_lval.cval = "";  
	return(FRAME); 	
}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 237 "gtkdialog_lexer.l"
{
	Token="<frame>";
	gtkdialog_lval.cval=strdup(&gtkdialog_text[7]);  
	gtkdialog_lval.cval[strlen(gtkdialog_lval.cval)-1] = 0;
	return FRAME; 
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 244 "gtkdialog_lexer.l"
{ 
	Token="</frame>"; 
	return(EFRAME);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 250 "gtkdialog_lexer.l"
{ 
	Token="<text>"; 
	return(TEXT);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 255 "gtkdialog_lexer.l"
{ 
	Token="<text>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_TEXT);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 261 "gtkdialog_lexer.l"
{ 
	Token="</text>"; 
	return(ETEXT);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 267 "gtkdialog_lexer.l"
{ 
	Token="<pixmap>"; 
	return(PIXMAP);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 272 "gtkdialog_lexer.l"
{ 
	Token="</pixmap>"; 
	return(EPIXMAP); 
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 277 "gtkdialog_lexer.l"
{ 
	Token="<pixmap>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_PIXMAP);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 284 "gtkdialog_lexer.l"
{ 
	Token="<entry>"; 
	return(ENTRY);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 289 "gtkdialog_lexer.l"
{ 
	Token="</entry>"; 
	return(EENTRY);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 294 "gtkdialog_lexer.l"
{ 
	Token="<entry>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_ENTRY);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 301 "gtkdialog_lexer.l"
{ 
	Token="<edit>"; 
	return(EDIT);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 306 "gtkdialog_lexer.l"
{ 
	Token="<entry>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_EDIT);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 312 "gtkdialog_lexer.l"
{ 
	Token="</edit>"; 
	return(EEDIT);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 318 "gtkdialog_lexer.l"
{ 
	Token="<tree>";  
	return  TREE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 323 "gtkdialog_lexer.l"
{ 
	Token="<tree>";  
	BEGIN(ST_TAG_ATTR);
	return PART_TREE;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 329 "gtkdialog_lexer.l"
{
	Token="</tree>"; 
	return ETREE;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 335 "gtkdialog_lexer.l"
{ 
	Token="<chooser>"; 
	return(CHOOSER);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 340 "gtkdialog_lexer.l"
{ 
	Token="</chooser>"; 
	return(ECHOOSER);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 345 "gtkdialog_lexer.l"
{ 
	Token="<chooser>";  
	BEGIN(ST_TAG_ATTR);
	return PART_CHOOSER;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 352 "gtkdialog_lexer.l"
{ 
	Token="<button>"; 
	return(BUTTON);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 357 "gtkdialog_lexer.l"
{ 
	Token="</button>"; 
	return(EBUTTON);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 362 "gtkdialog_lexer.l"
{ 
	//g_message("PART_BUTTON: '%s'", gtkdialog_text);
	Token="<button>";  
	BEGIN(ST_TAG_ATTR);
	return PART_BUTTON;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 369 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONOK);  			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 370 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONCANCEL);  		}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 371 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONHELP);  		}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 372 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONYES);  		}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 373 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONNO);  			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 375 "gtkdialog_lexer.l"
{ Token="<checkbox>"; return(CHECKBOX);       		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 376 "gtkdialog_lexer.l"
{ Token="</checkbox>"; return(ECHECKBOX);     		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 377 "gtkdialog_lexer.l"
{ Token="<chackbox>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_CHECKBOX);  				}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 381 "gtkdialog_lexer.l"
{ Token="<radiobutton>"; return(RADIO);      		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 382 "gtkdialog_lexer.l"
{ Token="</radiobutton>"; return(ERADIO);    		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 383 "gtkdialog_lexer.l"
{ Token="<radiobutton>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_RADIO);  					}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 387 "gtkdialog_lexer.l"
{ Token="<progressbar>"; return(PROGRESS);      	}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 388 "gtkdialog_lexer.l"
{ Token="</progressbar>"; return(EPROGRESS);    	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 389 "gtkdialog_lexer.l"
{ Token="<progressbar>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_PROGRESS);  				}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 394 "gtkdialog_lexer.l"
{ Token="<radio>"; return(RADIO);  			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 395 "gtkdialog_lexer.l"
{ Token="</radio>"; return(ERADIO);  			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 397 "gtkdialog_lexer.l"
{ Token="<gvim>"; return(GVIM);  			}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 398 "gtkdialog_lexer.l"
{ Token="</gvim>"; return(EGVIM);  			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 400 "gtkdialog_lexer.l"
{ Token="<combobox>"; return(COMBO);  	  		}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 401 "gtkdialog_lexer.l"
{ Token="<combobox>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_COMBO); 					}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 404 "gtkdialog_lexer.l"
{ Token="</combobox>"; return(ECOMBO);    		}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 406 "gtkdialog_lexer.l"
{ Token="<list>";  return(LIST);  			}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 407 "gtkdialog_lexer.l"
{ Token="<list>";  
					  BEGIN(ST_TAG_ATTR);
					  return(PART_LIST); 					}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 410 "gtkdialog_lexer.l"
{ Token="</list>"; return(ELIST);  			}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 412 "gtkdialog_lexer.l"
{ Token="<table>"; return(TABLE);  			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 413 "gtkdialog_lexer.l"
{ Token="</table>"; return(ETABLE);  			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 415 "gtkdialog_lexer.l"
{ Token="<menubar>"; return(MENUBAR);  			}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 416 "gtkdialog_lexer.l"
{ Token="</menubar>"; return(EMENUBAR);			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 418 "gtkdialog_lexer.l"
{ Token="<menu>"; return(MENU);  			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 419 "gtkdialog_lexer.l"
{ Token="</menu>"; return(EMENU);			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 421 "gtkdialog_lexer.l"
{ Token="<menuitem>"; return(MENUITEM);  		}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 422 "gtkdialog_lexer.l"
{ Token="<menuitem>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_MENUITEM);  				}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 425 "gtkdialog_lexer.l"
{ Token="</menuitem>"; return(EMENUITEM);		}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 427 "gtkdialog_lexer.l"
{ Token="<separator>"; return(SEPARATOR);  		}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 428 "gtkdialog_lexer.l"
{ Token="</separator>"; return(ESEPARATOR);		}
	YY_BREAK
/* Thunor: Newly supported widgets */
case 92:
YY_RULE_SETUP
#line 431 "gtkdialog_lexer.l"
{ Token="<hseparator>"; return(HSEPARATOR); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 432 "gtkdialog_lexer.l"
{ Token="</hseparator>"; return(EHSEPARATOR); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 433 "gtkdialog_lexer.l"
{ Token="<hseparator>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_HSEPARATOR); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 437 "gtkdialog_lexer.l"
{ Token="<vseparator>"; return(VSEPARATOR); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 438 "gtkdialog_lexer.l"
{ Token="</vseparator>"; return(EVSEPARATOR); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 439 "gtkdialog_lexer.l"
{ Token="<vseparator>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_VSEPARATOR); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 449 "gtkdialog_lexer.l"
{ Token="<label>"; return(LABEL);    			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 450 "gtkdialog_lexer.l"
{ Token="</label>"; return(ELABEL);  			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 452 "gtkdialog_lexer.l"
{ Token="<item>"; return(ITEM);      			}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 453 "gtkdialog_lexer.l"
{ Token="</item>"; return(EITEM);    			}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 454 "gtkdialog_lexer.l"
{ Token="<item>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_ITEM); 					}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 458 "gtkdialog_lexer.l"
{ Token="<default>"; return(DEFAULT);  			}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 459 "gtkdialog_lexer.l"
{ Token="</default>"; return(EDEFAULT);  		}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 461 "gtkdialog_lexer.l"
{ Token="<visible>"; return(VISIBLE);  			}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 462 "gtkdialog_lexer.l"
{ Token="</visible>"; return(EVISIBLE);  		}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 464 "gtkdialog_lexer.l"
{ 
					  Token="<variable>"; 
					  return(VARIABLE); 					}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 467 "gtkdialog_lexer.l"
{ 
					  Token="</variable>"; 
					  return(EVARIABLE); 					}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 471 "gtkdialog_lexer.l"
{ Token="<height>"; return(HEIGHT);  			}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 472 "gtkdialog_lexer.l"
{ Token="</height>"; return(EHEIGHT);  			}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 474 "gtkdialog_lexer.l"
{ Token="<width>"; return(WIDTH);   			}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 475 "gtkdialog_lexer.l"
{ Token="</width>"; return(EWIDTH);   			}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 477 "gtkdialog_lexer.l"
{ Token="<input>"; return(INPUT);   			}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 478 "gtkdialog_lexer.l"
{ Token="</input>"; return(EINPUT);   			}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 479 "gtkdialog_lexer.l"
{ Token="<input file>"; return(INPUTFILE);   		}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 480 "gtkdialog_lexer.l"
{ Token="<input file>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_INPUTFILE);   				}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 483 "gtkdialog_lexer.l"
{ Token="<input>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_INPUT);   				}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 487 "gtkdialog_lexer.l"
{ Token="<output>"; return(OUTPUT);   			}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 488 "gtkdialog_lexer.l"
{ Token="</output>"; return(EOUTPUT);   		}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 489 "gtkdialog_lexer.l"
{ Token="<output>"; return(OUTPUTFILE);   		}
	YY_BREAK
/*
	** The definition of action tags.
	*/
case 121:
YY_RULE_SETUP
#line 494 "gtkdialog_lexer.l"
{ 
	Token="<action>"; 
	return(ACTION);
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 499 "gtkdialog_lexer.l"
{ 
	Token="<action>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_ACTION);
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 505 "gtkdialog_lexer.l"
{ 
	Token="</action>"; 
	return(EACTION);
}
	YY_BREAK
case 124:
/* rule 124 can match eol */
YY_RULE_SETUP
#line 515 "gtkdialog_lexer.l"
{ 
	Token=g_strdup(gtkdialog_text); 
	gtkdialog_error("Unknown end tag.");  
}
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
#line 520 "gtkdialog_lexer.l"
{ 
	Token=g_strdup(gtkdialog_text); 
	gtkdialog_error("Unknown tag.");      
}
	YY_BREAK
/*
					 * The quoted string. It can contain anything, except
					 * unescaped double quote.
					 */
case 126:
YY_RULE_SETUP
#line 529 "gtkdialog_lexer.l"
{
					  Token = "double quote";
					  BEGIN(ST_QUOTED_STRING);				}
	YY_BREAK
case 127:
/* rule 127 can match eol */
YY_RULE_SETUP
#line 533 "gtkdialog_lexer.l"
{
					  yymore();						}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 536 "gtkdialog_lexer.l"
{
					  yymore();						}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 539 "gtkdialog_lexer.l"
{
					  Token = gtkdialog_text;
					  gtkdialog_lval.cval = g_strdup(gtkdialog_text);
					  gtkdialog_lval.cval[strlen(gtkdialog_lval.cval) - 1] = '\0';
					  BEGIN(0);
					  return STRING;
					  							}
	YY_BREAK
/*
					 * An unquoted string can contain anything except 
					 * unescaped '<'.
					 */
case 130:
YY_RULE_SETUP
#line 551 "gtkdialog_lexer.l"
{
					  Token = "string";
					  BEGIN(ST_STRING);
					  yymore();
												}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 556 "gtkdialog_lexer.l"
{
					  Token = "string";
					  yymore();
												}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 562 "gtkdialog_lexer.l"
{
					  yymore();
												}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 566 "gtkdialog_lexer.l"
{
					  yymore();
												}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 570 "gtkdialog_lexer.l"
{
					  gtkdialog_lval.cval = g_strdup(gtkdialog_text);
					  gtkdialog_lval.cval[strlen(gtkdialog_lval.cval) - 1] = '\0';
					  unput('<');
					  BEGIN(0);
					  return STRING;
					  							}
	YY_BREAK
case 135:
/* rule 135 can match eol */
YY_RULE_SETUP
#line 580 "gtkdialog_lexer.l"
{
					  ++linenumber;
												}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 583 "gtkdialog_lexer.l"
{
					  /* */
												}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 587 "gtkdialog_lexer.l"
{
					  /* we do nothing, this is a dropped char. */
												}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 590 "gtkdialog_lexer.l"
ECHO;
	YY_BREAK
#line 2357 "gtkdialog_lexer.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(EMBEDDED):
			case YY_STATE_EOF(ST_TAG_ATTR):
			case YY_STATE_EOF(ST_QUOTED_TAGATTR):
			case YY_STATE_EOF(ST_STRING):
			case YY_STATE_EOF(ST_QUOTED_STRING):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed gtkdialog_in at a new source and called
			 * gtkdialog_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = gtkdialog_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( gtkdialog_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * gtkdialog_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of gtkdialog_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			gtkdialog_restart(gtkdialog_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) gtkdialog_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 669 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 669 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 668);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up gtkdialog_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					gtkdialog_restart(gtkdialog_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( gtkdialog_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve gtkdialog_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void gtkdialog_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        gtkdialog_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE );
	}

	gtkdialog__init_buffer(YY_CURRENT_BUFFER,input_file );
	gtkdialog__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void gtkdialog__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		gtkdialog_pop_buffer_state();
	 *		gtkdialog_push_buffer_state(new_buffer);
     */
	gtkdialog_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	gtkdialog__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (gtkdialog_wrap()) processing, but the only time this flag
	 * is looked at is after gtkdialog_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void gtkdialog__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	gtkdialog_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE gtkdialog__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) gtkdialog_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) gtkdialog_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__create_buffer()" );

	b->yy_is_our_buffer = 1;

	gtkdialog__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with gtkdialog__create_buffer()
 * 
 */
    void gtkdialog__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		gtkdialog_free((void *) b->yy_ch_buf  );

	gtkdialog_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a gtkdialog_restart() or at EOF.
 */
    static void gtkdialog__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	gtkdialog__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then gtkdialog__init_buffer was _probably_
     * called from gtkdialog_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void gtkdialog__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		gtkdialog__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void gtkdialog_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	gtkdialog_ensure_buffer_stack();

	/* This block is copied from gtkdialog__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from gtkdialog__switch_to_buffer. */
	gtkdialog__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void gtkdialog_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	gtkdialog__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		gtkdialog__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void gtkdialog_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)gtkdialog_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gtkdialog_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)gtkdialog_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gtkdialog_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE gtkdialog__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) gtkdialog_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	gtkdialog__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to gtkdialog_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       gtkdialog__scan_bytes() instead.
 */
YY_BUFFER_STATE gtkdialog__scan_string (yyconst char * yystr )
{
    
	return gtkdialog__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to gtkdialog_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE gtkdialog__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) gtkdialog_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = gtkdialog__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in gtkdialog__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gtkdialog_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		gtkdialog_text[gtkdialog_leng] = (yy_hold_char); \
		(yy_c_buf_p) = gtkdialog_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		gtkdialog_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int gtkdialog_get_lineno  (void)
{
        
    return gtkdialog_lineno;
}

/** Get the input stream.
 * 
 */
FILE *gtkdialog_get_in  (void)
{
        return gtkdialog_in;
}

/** Get the output stream.
 * 
 */
FILE *gtkdialog_get_out  (void)
{
        return gtkdialog_out;
}

/** Get the length of the current token.
 * 
 */
int gtkdialog_get_leng  (void)
{
        return gtkdialog_leng;
}

/** Get the current token.
 * 
 */

char *gtkdialog_get_text  (void)
{
        return gtkdialog_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void gtkdialog_set_lineno (int  line_number )
{
    
    gtkdialog_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see gtkdialog__switch_to_buffer
 */
void gtkdialog_set_in (FILE *  in_str )
{
        gtkdialog_in = in_str ;
}

void gtkdialog_set_out (FILE *  out_str )
{
        gtkdialog_out = out_str ;
}

int gtkdialog_get_debug  (void)
{
        return gtkdialog__flex_debug;
}

void gtkdialog_set_debug (int  bdebug )
{
        gtkdialog__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from gtkdialog_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    gtkdialog_in = stdin;
    gtkdialog_out = stdout;
#else
    gtkdialog_in = (FILE *) 0;
    gtkdialog_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * gtkdialog_lex_init()
     */
    return 0;
}

/* gtkdialog_lex_destroy is for both reentrant and non-reentrant scanners. */
int gtkdialog_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		gtkdialog__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		gtkdialog_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	gtkdialog_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    gtkdialog_free ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * gtkdialog_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *gtkdialog_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *gtkdialog_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void gtkdialog_free (void * ptr )
{
	free( (char *) ptr );	/* see gtkdialog_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 590 "gtkdialog_lexer.l"



static gchar *
process_string(gchar *str)
{
	//fprintf(stderr, "%s(): Input = '%s'\n", __func__, str);
	// FIXME: Well, this will come tomorrow...
	return g_strdup(str);
}


