#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <edit>
    <variable>EDITOR</variable>
    <width>350</width><height>150</height>
    <default>
"This is the default text of the editor."
    </default>
  </edit>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
