#!/bin/sh

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window>
	<vbox>
		<edit editable="false">
			<variable>EDIT0</variable>
			<height>50</height>
			<width>350</width>
			<default>editable is false</default>
		</edit>
		<edit accepts-tab="false">
			<variable>EDIT1</variable>
			<height>50</height>
			<width>350</width>
			<default>accepts-tab is false</default>
		</edit>
		<edit indent="25">
			<variable>EDIT2</variable>
			<height>50</height>
			<width>350</width>
			<default>indent is 25</default>
		</edit>
		<edit left-margin="25" right-margin="25">
			<variable>EDIT3</variable>
			<height>50</height>
			<width>350</width>
			<default>left-margin and right-margin is 25</default>
		</edit>
		<edit cursor-visible="false">
			<variable>EDIT4</variable>
			<height>50</height>
			<width>350</width>
			<default>cursor-visible is false</default>
		</edit>
		<hbox>
			<button cancel></button>
			<button ok></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
