#!/bin/sh

## Get the font family from the target TrueType font.
## On entry: $1 = filename
##  On exit: FontFamily will be initialised

funcFontFamilyInit() {
	if [ -z "$BASH" ]; then local FUNCNAME=funcFontFamilyInit; fi
	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME(): IN"; fi

	## Local variables.
	local family

	if [ `command -v fc-query` ]; then
		family="`fc-query \"$1\" | grep family:`"
		if [ $? -eq 0 ]; then
			family=${family#*\"}
			family=${family%\"*}
			FontFamily=$family
		else
			FontFamily="$i18nInvalid_font"
		fi
	else
		FontFamily="$i18nfc_query_not_found"
	fi

	if [ $DEBUG_CONTENT -ne 0 ]; then
		echo "$FUNCNAME(): FontFamily=$FontFamily"
	fi

	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME(): OUT"; fi
}
