#!/bin/sh

## Internationalise everything necessary.

funci18n() {
	if [ -z "$BASH" ]; then local FUNCNAME=funci18n; fi
	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME(): IN"; fi

	## Default to English.
	i18nFamily="Family"
	i18nPangram="The quick brown fox jumps over the lazy dog"
	i18nPreview="Preview"
	i18nInvalid_font="Invalid font"
	i18nfc_query_not_found="fc-query not found"
	case ${LANG%%_*} in
		de)
			#i18nFamily=""
			#i18nPangram=""
			#i18nPreview=""
			#i18nInvalid_font=""
			#i18nfc_query_not_found=""
			;;
		fr)
			#i18nFamily=""
			#i18nPangram=""
			#i18nPreview=""
			#i18nInvalid_font=""
			#i18nfc_query_not_found=""
			;;
	esac

	if [ $DEBUG_TRANSITS -ne 0 ]; then echo "$FUNCNAME(): OUT"; fi
}
