#!/bin/sh

# Thunor: This example is broken: input from a command has not been
# implemented for this widget and it's now old and deprecated.

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <hbox>
    <text>
      <label>Combobox:</label>
    </text>
    <combobox>
      <variable>COMBOBOX</variable>
      <input>ls</input>
    </combobox>
  </hbox>
  <hbox>
    <button ok></button>
    <button cancel></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
