#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <chooser>
    <height>500</height><width>600</width>
    <variable>CHOOSER</variable>
  </chooser>
  <hbox>
    <button help></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
