#!/bin/sh

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window>
	<vbox>
		<frame Frame1>
			<text><label>Label1</label></text>
			<entry></entry>
		</frame>
		<frame Frame2>
			<hbox>
				<text><label>Label2</label></text>
				<entry></entry>
			</hbox>
		</frame>
		<hbox>
			<button cancel></button>
			<button help></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
