#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <frame Frame1>
    <text><label>Label1</label></text>
    <entry></entry>
  </frame>
  <frame Frame2>
    <hbox>
      <text><label>Label2</label></text>
      <entry></entry>
    </hbox>
  </frame>
  <hbox>
    <button cancel></button>
    <button help></button>
  </hbox>
</vbox>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
