#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<window>
	<vbox>
		<table>
			<width>500</width><height>200</height>
			<variable>TABLE</variable>
			<label>Header of Column 1|Header of Column 2|Header of Column 3</label>
			<item>First item |Row 1 Column 2 |Row 1 Column 3</item>
			<item>Second item|Row 2 Column 2 |Row 2 Column 3</item>
			<item>Third item |Row 3 Column 2 |Row 3 Column 3</item>
			<action>echo $TABLE</action>
		</table>
		<hbox>
			<button ok></button>
			<button cancel></button>
		</hbox>
	</vbox>
</window>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
