#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <entry>
    <default>Default value</default>
    <variable>ENTRY</variable>
  </entry>
  <hbox>
    <button ok></button>
    <button cancel></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
