#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<window>
	<vbox>
		<hbox>
			<text>
				<label>whoami:</label>
			</text>
			<entry>
				<input>whoami</input>
				<variable>ENTRY</variable>
			</entry>
		</hbox>
		<hbox>
			<button ok></button>
			<button cancel></button>
		</hbox>
	</vbox>
</window>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
