#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <hbox>
    <text>
      <label>whoami:</label>
    </text>
    <entry>
      <input>whoami</input>
      <variable>ENTRY</variable>
    </entry>
  </hbox>
  <hbox>
    <button ok></button>
    <button cancel></button>
  </hbox>
</vbox>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
