#!/bin/sh

#
# The <item> tag can hold the following attributes:
#   o stock or stock_id
#   o icon or icon_name
#

GTKDIALOG=gtkdialog

export TMPDIR=/tmp/gtkdialog/examples/"$(basename $0)"
mkdir -p "$TMPDIR"

cat <<EOF > "$TMPDIR"/list.txt
gtk-cdrom    | CD_ROM Drive  | /cdrom/    | ak.tex
gtk-floppy   | Floppy Disk   | /floppy/   | ak.dvi
gtk-harddisk | Hard Disk     | /harddisk/ | ak.ps
gtk-network  | Network Drive | /network/  | ak.pdf
gtk-delete   | Trash         | /trash/    | 
EOF

export MAIN_DIALOG='
<vbox>
  <tree>
    <input file stock_column="0">'"$TMPDIR"'/list.txt</input>
    <label>Device                        | Directory | File</label>
    <item stock_id="gtk-floppy">Floppy Disk | /floppy/  | ak.tex</item>
    <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.dvi</item>
    <item icon="pdf">Floppy Disk | /floppy/  | ak.ps</item>
    <item icon_name="rpm">Floppy Disk | /floppy/  | ak.pdf</item>
    <item stock="gtk-cdrom">CD_ROM Drive | /cdrom/   | </item>
    <height>250</height><width>400</width>
    <variable>TREE2</variable>
  </tree>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG 
