#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <frame Tree With Actions>
    <text>
      <label>The exported column is column "One"  </label>
    </text>
    <tree rules_hint="true" exported_column="0">
      <label>One     | Two     | Three </label>
      <item stock="gtk-yes">r1c1|r1c2|r1c3</item>
      <item stock="gtk-no">r2c1|r2c2|r2c3</item>
      <item stock="gtk-no">r3c1|r3c2|r3c3</item>
      <variable>TREE1</variable>
      <height>100</height><width>200</width>
      <action>echo action[Double Click]: $TREE1</action>
      <action signal="button-press-event">echo button-press-event[BUTTON=$BUTTON]: $TREE1</action>
      <action signal="cursor_changed">echo cursor_changed: $TREE1</action>
      <action signal="button-release-event">echo button-release-event[BUTTON=$BUTTON]: $TREE1; echo</action>
    </tree>
  </frame>
  <frame Another Tree With Actions>
    <text>
      <label>The exported column is column "Three"  </label>
    </text>
    <tree rules_hint="true" exported_column="2">
      <label>One     | Two     | Three </label>
      <item>r1c1|r1c2|r1c3</item>
      <item>r2c1|r2c2|r2c3</item>
      <item>r3c1|r3c2|r3c3</item>
      <variable>TREE2</variable>
      <height>100</height><width>200</width>
      <action>echo action[Double Click]: $TREE2</action>
      <action signal="button-press-event">echo button-press-event[BUTTON=$BUTTON]: $TREE2</action>
      <action signal="cursor_changed">echo cursor_changed: $TREE2</action>
      <action signal="button-release-event">echo button-release-event[BUTTON=$BUTTON]: $TREE2; echo</action>
    </tree>
  </frame>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
