#!/bin/sh

# Thunor: This won't work on *nix as the "insert/append" function has
# only been written for G_OS_WIN32 -- I don't know why that is.

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <frame Insert and Remove>
    <tree rules_hint="true" headers_visible="false">
      <label>This label is invisible but required</label>
      <height>100</height><width>400</width>
      <variable>TREE</variable>
    </tree>
    <hbox>
      <entry>
        <variable>ENTRY</variable>
      </entry>
      <button>
        <input file stock="gtk-add"></input>
        <action type="insert">ENTRY,TREE</action>
      </button>
      <button>
        <input file stock="gtk-remove"></input>
        <action type="removeselected">TREE</action>
      </button>
    </hbox>    
  </frame>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
