#!/bin/sh

#
# The <input> tags can have attributes setting which input column holds the
# icon information:
#   o stock_column
#   o icon_column
#

GTKDIALOG=gtkdialog

list() {
  echo "gtk-open | | gtk-open | 2 "
  echo "gtk-about | | gtk-about | 2 "
  echo "gtk-add | | gtk-add | 2 "
  echo "gtk-apply | | gtk-apply | 2 "
  echo "gtk-bold | | gtk-bold | 2 "
  echo "gtk-cancel | | gtk-cancel | 2 "
  echo "gtk-cdrom | | gtk-cdrom | 2 "
  echo "gtk-clear | | gtk-clear | 2 "
  echo "gtk-close | | gtk-close | 2 "
  echo "gtk-color-picker | | gtk-color-picker | 2 "
  echo "gtk-convert | | gtk-convert | 2 "
}; export -f list

export MAIN_DIALOG='
<vbox>
  <hbox>
    <frame Stock icons from input command>
      <tree>
        <label>0 | 1 | 2</label>
        <input stock_column="0">list</input>
        <height>350</height><width>250</width>
        <variable>TREE1</variable>
      </tree>
    </frame>
    <frame Theme icons from input command>
      <tree stock="gtk-file">
        <label>0 | 1 | 2</label>
        <input icon_column="0">list</input>
        <height>350</height><width>250</width>
        <variable>TREE2</variable>
      </tree>
    </frame>
  </hbox>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG 
