#!/bin/sh

# Thunor: This example is broken: the action appears to be the cause.

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <list>
    <variable>LIST</variable>
    <item>First item</item>
    <item>Second item</item>
    <item>Third item</item>
    <action>echo Chosen item is $LIST</action>
  </list>
  <hbox>
    <button ok></button>
    <button cancel></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
