#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <list>
    <variable>LIST</variable>
    <item>First item</item>
    <item>Second item</item>
    <item>Third item</item>
    <action>echo Chosen item is $LIST</action>
  </list>
  <hbox>
    <button ok></button>
    <button cancel></button>
  </hbox>
</vbox>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
