#!/bin/sh

# This example requires GTK+ 2.

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window>
	<vbox>
		<hbox>
			<text>
				<label>Combobox:</label>
			</text>
			<combobox>
				<variable>COMBOBOX</variable>
				<item>First item</item>
				<item>Second item</item>
				<item>Third item</item>
			</combobox>
		</hbox>
		<hbox>
			<button ok></button>
			<button cancel></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
