#!/bin/sh

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window>
	<vbox>
		<frame Icon name examples>
			<tree rules-hint="true">
				<height>400</height>
				<width>250</width>
				<label>Icon Name</label>
				<item icon-name="gimp">gimp</item>
				<item icon-name="gnumeric">gnumeric</item>
				<item icon-name="geany">geany</item>
				<item icon-name="glade-3">glade-3</item>
				<item icon-name="uget-icon">uget-icon</item>
				<item icon-name="viewnior">viewnior</item>
				<item icon-name="xarchive">xarchive</item>
				<item icon-name="scribus">scribus</item>
				<item icon-name="inkscape">inkscape</item>
				<item icon-name="html">html</item>
				<item icon-name="gz">gz</item>
				<item icon-name="top">top</item>
				<item icon-name="midori">midori</item>
				<item icon-name="adblock">adblock</item>
				<item icon-name="abiword">abiword</item>
			</tree>
		</frame>
		<hbox homogeneous="true">
			<button ok></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
