#!/bin/sh

GTKDIALOG=gtkdialog

#
# stock_column
# icon_column
#

function list() {
  ls -lha | grep ^d | awk '{print "dir_o|" $1 "|" $8}'
  ls -lha | grep ^- | awk '{print "gexec|" $1 "|" $8}'
}; export -f list

export MAIN_DIALOG='
<vbox>
  <tree>
    <label>Permissions|Filename</label>
    <input icon_column="0">list</input>
    <height>150</height><width>500</width>
    <variable>TREE1</variable>
  </tree>
  <tree stock="gtk-file">
    <label>Icon Name|Permissions|Filename</label>
    <input>list</input>
    <height>150</height><width>500</width>
    <variable>TREE2</variable>
  </tree>
  <tree>
    <label>Device                        | Directory | File</label>
    <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.tex</item>
    <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.dvi</item>
    <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.ps</item>
    <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.pdf</item>
    <item stock="gtk-cdrom">CD_ROM Drive | /cdrom/   | </item>
    <height>150</height><width>500</width>
    <variable>TREE3</variable>
  </tree>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG 
