#!/bin/sh

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window>
	<vbox>
		<frame Tree With Actions>
			<text>
				<label>The exported column is column "One"  </label>
			</text>
			<tree rules-hint="true" exported-column="0">
				<variable>TREE1</variable>
				<height>100</height>
				<width>200</width>
				<label>One     | Two     | Three </label>
				<item stock-id="gtk-yes">r1c1|r1c2|r1c3</item>
				<item stock-id="gtk-no">r2c1|r2c2|r2c3</item>
				<item stock-id="gtk-no">r3c1|r3c2|r3c3</item>
				<action>echo action[Double Click]: $TREE1</action>
				<action signal="button-press-event">echo button-press-event[BUTTON=$BUTTON]: $TREE1</action>
				<action signal="cursor-changed">echo cursor-changed: $TREE1</action>
				<action signal="button-release-event">echo button-release-event[BUTTON=$BUTTON]: $TREE1; echo</action>
			</tree>
		</frame>
		<frame Another Tree With Actions>
			<text>
				<label>The exported column is column "Three"  </label>
			</text>
			<tree rules-hint="true" exported-column="2">
				<variable>TREE2</variable>
				<height>100</height>
				<width>200</width>
				<label>One     | Two     | Three </label>
				<item>r1c1|r1c2|r1c3</item>
				<item>r2c1|r2c2|r2c3</item>
				<item>r3c1|r3c2|r3c3</item>
				<action>echo action[Double Click]: $TREE2</action>
				<action signal="button-press-event">echo button-press-event[BUTTON=$BUTTON]: $TREE2</action>
				<action signal="cursor-changed">echo cursor-changed: $TREE2</action>
				<action signal="button-release-event">echo button-release-event[BUTTON=$BUTTON]: $TREE2; echo</action>
			</tree>
		</frame>
		<hbox homogeneous="true">
			<button ok></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
