#!/bin/sh

GTKDIALOG=gtkdialog

#
# The <tree> tag can hold the following attributes for using as a default icon:
#   o stock or stock_id
#   o icon or icon_name
#

TMPDIR=/tmp/gtkdialog/examples/tree
mkdir -p "$TMPDIR"
cat <<EOF > "$TMPDIR"/list.txt
gtk-cdrom    | CD_ROM Drive  | /cdrom/    | ak.tex
gtk-floppy   | Floppy Disk   | /floppy/   | ak.dvi
gtk-harddisk | Hard Disk     | /harddisk/ | ak.ps
gtk-network  | Network Drive | /network/  | ak.pdf
gtk-delete   | Trash         | /trash/    | 
EOF

export MAIN_DIALOG='
<vbox>
  <tree stock="gtk-apply">
    <input file stock_column="0">'"$TMPDIR"'/list.txt</input>
    <label>Device                        | Directory | File</label>
    <item>Floppy Disk | /floppy/  | ak.tex</item>
    <item>Floppy Disk | /floppy/  | ak.dvi</item>
    <item icon="scribus">Floppy Disk | /floppy/  | ak.ps</item>
    <item icon_name="top">Floppy Disk | /floppy/  | ak.pdf</item>
    <item stock="gtk-cdrom">CD_ROM Drive | /cdrom/   | </item>
    <height>250</height><width>400</width>
    <variable>TREE1</variable>
  </tree>
  <tree icon_name="xarchive">
    <input file stock_column="0">'"$TMPDIR"'/list.txt</input>
    <label>Device                        | Directory | File</label>
    <item>Floppy Disk | /floppy/  | ak.tex</item>
    <item>Floppy Disk | /floppy/  | ak.dvi</item>
    <item icon="abiword">Floppy Disk | /floppy/  | ak.ps</item>
    <item icon_name="geany">Floppy Disk | /floppy/  | ak.pdf</item>
    <item stock="gtk-cdrom">CD_ROM Drive | /cdrom/   | </item>
    <height>250</height><width>400</width>
    <variable>TREE2</variable>
  </tree>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG 
