#!/bin/sh

GTKDIALOG=gtkdialog

export TMPDIR=/tmp/gtkdialog/examples/"$(basename $0)"
mkdir -p "$TMPDIR"

cat <<EOF > "$TMPDIR"/list.txt
gtk-cdrom    | CD_ROM Drive  | /cdrom/    | ak.tex
gtk-floppy   | Floppy Disk   | /floppy/   | ak.dvi
gtk-harddisk | Hard Disk     | /harddisk/ | ak.ps
gtk-network  | Network Drive | /network/  | ak.pdf
gtk-delete   | Trash         | /trash/    | 
EOF

export MAIN_DIALOG='
<vbox>
  <frame With Rules, Without Headers>
    <tree rules_hint="true" headers_visible="false">
      <input file stock_column="0">'"$TMPDIR"'/list.txt</input>
      <label>Device                        | Directory | File</label>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.tex</item>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.dvi</item>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.ps</item>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.pdf</item>
      <item stock="gtk-cdrom">CD_ROM Drive | /cdrom/   | </item>
      <height>250</height><width>400</width>
      <variable>TREE</variable>
    </tree>
  </frame>
  <frame Hover Mode>
    <tree hover_expand="true" hover_selection="true">
      <input file stock_column="0">'"$TMPDIR"'/list.txt</input>
      <label>Device                        | Directory | File</label>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.tex</item>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.dvi</item>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.ps</item>
      <item stock="gtk-floppy">Floppy Disk | /floppy/  | ak.pdf</item>
      <item stock="gtk-cdrom">CD_ROM Drive | /cdrom/   | </item>
      <height>250</height><width>400</width>
      <variable>TREE</variable>
    </tree>
  </frame>
  <hbox>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
