#!/bin/sh

# Thunor: I'm not sure that this example is doing what was originally intended.
# The label isn't resizing with the window (Gtkdialog's support for resizing
# requires attention) and both "fill" and "expand" default to true anyway.

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window>
	<vbox>
		<frame Space>
			<hbox spacing="10">
				<text><label>spacing</label></text>
				<entry></entry>
			</hbox>
			<hbox homogeneous="true">
				<text><label>homogeneous</label></text>
				<entry></entry>
			</hbox>
		</frame>
		<frame Description>
			<hbox>
				<pixmap>
					<input file stock="gtk-info"></input>
				</pixmap>
				<text>
					<label>"This is a label with a rather long text, so it must be wrapped as the user resizes the window. However, the default label width is 30 characters."
					</label>
				</text>
			</hbox>
		</frame>
		<frame Description>
			<hbox fill="true" expand="true">
				<pixmap>
					<input file stock="gtk-info"></input>
				</pixmap>
				<text>
					<label>"This is a label with a rather long text, so it must be wrapped as the user resizes the window. However, the default label width is 30 characters."
					</label>
				</text>
			</hbox>
		</frame>
		<hbox>
			<button cancel></button>
			<button help></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
