#!/bin/sh

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window>
	<vbox>
		<frame Radiobutton attributes example>
			<radiobutton active="true">
				<label>Radiobutton with active set to true</label>
				<variable>RADIOBUTTON1</variable>
				<action>echo Radiobutton is $RADIOBUTTON1 now.</action>
			</radiobutton>
			<radiobutton draw_indicator="false">
				<label>Radiobutton with draw_indicator set to false</label>
				<variable>RADIOBUTTON2</variable>
				<action>echo Radiobutton is $RADIOBUTTON2 now.</action>
			</radiobutton>
			<radiobutton inconsistent="true">
				<label>Radiobutton with inconsistent set to true</label>
				<variable>RADIOBUTTON3</variable>
				<action>echo Radiobutton is $RADIOBUTTON3 now.</action>
			</radiobutton>
		</frame>
		<hbox>
			<button ok>
				<variable>OKBUTTON</variable>
			</button>
			<button cancel></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
