#!/bin/bash

# This example requires bash.

GTKDIALOG=gtkdialog

print_this() {
	echo "print: $1"
}; export -f print_this

export MAIN_DIALOG='
<window>
	<vbox>
		<button>
			<label>function</label>
			<action>print_this button</action>
		</button>
		<button>
			<label>Exit</label>
		</button>
	</vbox>
</window>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
