#!/bin/sh

# Thunor: I'm not sure that this example is doing what was originally intended.

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <hbox>
    <text>
      <label>Input:</label>
    </text>
    <entry>
      <variable>ENTRY</variable>
    </entry>
  </hbox>
  <hbox>
    <button help></button>
    <button cancel></button>
    <button ok></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
