#!/bin/sh

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

IMAGEFILE="`find /usr/share/pixmaps -maxdepth 1 -type f | head -1`"

MAIN_DIALOG='
<window>
	<vbox>
		<hbox>
			<frame Pixmap from stock icon_size="1">
				<pixmap icon_size="1">
					<input file stock="gtk-save"></input>
				</pixmap>
			</frame>
			<frame Pixmap from stock icon_size="3">
				<pixmap icon_size="3">
					<input file stock="gtk-save"></input>
				</pixmap>
			</frame>
		</hbox>
		<hbox>
			<frame Pixmap from stock icon_size="5">
				<pixmap icon_size="5">
					<input file stock="gtk-save"></input>
				</pixmap>
			</frame>
			<frame Pixmap from stock icon_size="6">
				<pixmap icon_size="6">
					<input file stock="gtk-save"></input>
				</pixmap>
			</frame>
		</hbox>
		<hbox>
			<frame Pixmap from file>
				<pixmap>
					<input file>'"$IMAGEFILE"'</input>
				</pixmap>
			</frame>
			<frame Pixmap from file scaled>
				<pixmap>
					<width>128</width>
					<input file>'"$IMAGEFILE"'</input>
				</pixmap>
			</frame>
		</hbox>
		<hbox>
			<button cancel></button>
			<button ok></button>
		</hbox>
	</vbox>
</window>
'

export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
