#!/bin/sh

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window title="MenuItemSeparator" resizable="false" width-request="360" height-request="240"  border-width="0">
	<vbox spacing="0">
		<menubar>
			<menu use-underline="true">
				<menuitem stock-id="gtk-new" accel-key="0x4e" accel-mods="4">
				</menuitem>
				<menuitemseparator></menuitemseparator>
				<menuitem stock-id="gtk-open" accel-key="0x4f" accel-mods="4">
				</menuitem>
				<menuitemseparator></menuitemseparator>
				<menuitem stock-id="gtk-save" accel-key="0x53" accel-mods="4">
				</menuitem>
				<menuitemseparator></menuitemseparator>
				<menuitem stock-id="gtk-print" accel-key="0x50" accel-mods="4">
				</menuitem>
				<menuitemseparator></menuitemseparator>
				<menuitem stock-id="gtk-close" label="Close Ot_her Documents">
				</menuitem>
				<menuitemseparator></menuitemseparator>
				<menuitem stock-id="gtk-quit" accel-key="0x51" accel-mods="4">
					<action>exit:Quit</action>
				</menuitem>
				<label>"_File"</label>
			</menu>
		</menubar>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
