#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <list selection-mode="3">
    <variable>LIST</variable>
    <item>First item</item>
    <item>Second item</item>
    <item>Third item</item>
  </list>
  <hbox>
    <button ok></button>
    <button cancel></button>
  </hbox>
</vbox>
'

$GTKDIALOG --program=MAIN_DIALOG
