#line 2 "gtkdialog_lexer.c"

#line 4 "gtkdialog_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer gtkdialog__create_buffer
#define yy_delete_buffer gtkdialog__delete_buffer
#define yy_flex_debug gtkdialog__flex_debug
#define yy_init_buffer gtkdialog__init_buffer
#define yy_flush_buffer gtkdialog__flush_buffer
#define yy_load_buffer_state gtkdialog__load_buffer_state
#define yy_switch_to_buffer gtkdialog__switch_to_buffer
#define yyin gtkdialog_in
#define yyleng gtkdialog_leng
#define yylex gtkdialog_lex
#define yylineno gtkdialog_lineno
#define yyout gtkdialog_out
#define yyrestart gtkdialog_restart
#define yytext gtkdialog_text
#define yywrap gtkdialog_wrap
#define yyalloc gtkdialog_alloc
#define yyrealloc gtkdialog_realloc
#define yyfree gtkdialog_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE gtkdialog_restart(gtkdialog_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int gtkdialog_leng;

extern FILE *gtkdialog_in, *gtkdialog_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gtkdialog_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up gtkdialog_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via gtkdialog_restart()), so that the user can continue scanning by
	 * just pointing gtkdialog_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when gtkdialog_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int gtkdialog_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow gtkdialog_wrap()'s to do buffer switches
 * instead of setting up a fresh gtkdialog_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void gtkdialog_restart (FILE *input_file  );
void gtkdialog__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE gtkdialog__create_buffer (FILE *file,int size  );
void gtkdialog__delete_buffer (YY_BUFFER_STATE b  );
void gtkdialog__flush_buffer (YY_BUFFER_STATE b  );
void gtkdialog_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void gtkdialog_pop_buffer_state (void );

static void gtkdialog_ensure_buffer_stack (void );
static void gtkdialog__load_buffer_state (void );
static void gtkdialog__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER gtkdialog__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE gtkdialog__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE gtkdialog__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE gtkdialog__scan_bytes (yyconst char *bytes,int len  );

void *gtkdialog_alloc (yy_size_t  );
void *gtkdialog_realloc (void *,yy_size_t  );
void gtkdialog_free (void *  );

#define yy_new_buffer gtkdialog__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        gtkdialog_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        gtkdialog_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *gtkdialog_in = (FILE *) 0, *gtkdialog_out = (FILE *) 0;

typedef int yy_state_type;

extern int gtkdialog_lineno;

int gtkdialog_lineno = 1;

extern char *gtkdialog_text;
#define yytext_ptr gtkdialog_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up gtkdialog_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	gtkdialog_leng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 132
#define YY_END_OF_BUFFER 133
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[349] =
    {   0,
      133,  124,  131,  132,  130,  131,  132,  129,  132,  120,
      131,  132,    2,  124,  131,  132,  131,  132,    1,  131,
      132,  131,  132,   17,  131,  132,    2,  131,  132,   14,
      131,  132,   16,  131,  132,   14,   15,  131,  132,   15,
      131,  132,    6,  131,  132,    3,  131,  132,    4,  131,
      132,    5,  131,  132,    7,  131,  132,    7,  130,  131,
      132,    7,  129,  132,    9,  131,  132,    2,    7,  131,
      132,  131,  132,  125,  131,  132,  125,  130,  131,  132,
        2,  125,  131,  132,  128,  131,  132,  131,  132,  121,
      131,  132,  121,  130,  131,  132,  121,  129,  132,  123,

      131,  132,    2,  121,  131,  132,  131,  132,  124,    2,
      124,    2,  119,   16,   15,    3,    7,    2,    7,    8,
      125,    2,  125,  127,  126,  127,  121,    2,  121,  122,
      118,  119,   19,  118,  119,   46,   45,  119,   73,  119,
       31,   30,  119,   96,   94,  119,   79,   78,  119,   85,
      119,   37,   36,  119,   49,   48,  119,   28,   27,  119,
       47,  118,  119,   74,  118,  119,   32,  118,  119,   95,
      118,  119,   80,  118,  119,   86,  118,  119,   38,  118,
      119,   50,  118,  119,   29,  118,  119,   44,   42,  119,
       33,  119,  111,  107,  119,   92,  119,   71,  119,   10,

      119,   81,  119,  105,  119,   43,  118,  119,   35,  118,
      119,  108,  118,  119,   93,  118,  119,   72,  118,  119,
       82,  118,  119,   20,  118,  119,  106,  118,  119,  116,
      115,  119,16440,   54,  119,  103,  119,  111,  112,  119,
       41,   39,  119,   22,   21,  119,  117,  118,  119,   55,
      118,  119,  104,  118,  119,  113,  118,  119,   40,  118,
      119,   23,  118,  119,16440, 8248,   53,   51,  119,   97,
      119,   34,   83,  119,   99,  119,   52,  118,  119,   18,
      118,  119,   98,  118,  119,   84,  118,  119,  100,  118,
      119,   64,   62,  119,   76,   75,  119,   88,   87,  119,

       26,   24,  119,  101,  119,   63,  118,  119,   77,  118,
      119,   89,  118,  119,   25,  118,  119,  102,  118,  119,
       61,   57,   90,  119,   91,  118,  119,   60,  110,  109,
       59,  114,   70,   68,  119,   67,   65,  119,   69,  118,
      119,   66,  118,  119,   58,   12,   13,   11
    } ;

static yyconst flex_int16_t yy_accept[628] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    5,    8,   10,   13,   17,   19,
       22,   24,   27,   30,   33,   36,   40,   43,   46,   49,
       52,   55,   58,   62,   65,   68,   72,   74,   77,   81,
       85,   88,   90,   93,   97,  100,  103,  107,  109,  110,
      112,  113,  113,  113,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  115,  116,  117,  118,  120,  121,
      122,  124,  125,  127,  128,  130,  131,  131,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,

      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  137,  139,  139,  139,  141,  142,  144,
      144,  144,  144,  145,  147,  147,  148,  150,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  153,
      155,  156,  158,  158,  159,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  164,  164,  164,
      167,  170,  170,  170,  173,  173,  176,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  182,  185,  185,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  189,  191,  191,  193,  193,  193,  194,  196,

      198,  198,  198,  198,  198,  198,  198,  200,  200,  200,
      202,  204,  204,  204,  204,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  209,  212,  212,  215,  218,  218,
      218,  218,  218,  218,  218,  221,  221,  221,  224,  224,
      224,  227,  230,  230,  231,  233,  234,  236,  236,  236,
      236,  236,  236,  236,  238,  238,  239,  239,  239,  239,
      239,  239,  241,  242,  244,  244,  244,  244,  244,  244,
      244,  245,  247,  250,  253,  253,  253,  253,  253,  253,
      256,  256,  256,  256,  259,  262,  262,  262,  262,  262,
      262,  265,  266,  266,  267,  267,  267,  267,  267,  267,

      267,  268,  270,  270,  270,  272,  273,  273,  273,  275,
      275,  275,  275,  275,  275,  275,  275,  277,  277,  277,
      280,  280,  283,  286,  289,  289,  289,  289,  289,  289,
      289,  292,  292,  292,  292,  292,  292,  293,  295,  296,
      298,  298,  298,  298,  299,  301,  302,  304,  304,  304,
      304,  304,  306,  306,  309,  312,  315,  318,  318,  318,
      318,  321,  321,  321,  322,  323,  323,  323,  323,  323,
      323,  323,  323,  325,  325,  325,  325,  328,  328,  328,
      329,  329,  329,  330,  331,  331,  331,  331,  331,  331,
      331,  331,  332,  332,  332,  333,  334,  336,  337,  339,

      339,  342,  345,  345,  345,  345,  345,  345,  346,  346,
      346,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      348,  348,  348,  348,  348,  349,  349
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    1,    1,    1,
        1,    7,    7,    8,    9,    8,   10,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    7,    1,   11,
       12,   13,    1,    1,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
        1,   15,    1,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   14,   26,   27,   28,   29,
       30,   31,   14,   32,   33,   34,   35,   36,   37,   38,
       39,   14,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    5,    1,
        6,    7,    8,    5,    9,   10,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[643] =
    {   0,
        0,   12,   25,   41,   57,   72,   86,  100,  114,  128,
      142,  156, 1111,    0, 1112, 1112, 1112,    5,  171, 1112,
     1112, 1112,   17, 1112, 1102,    0,    0, 1112,    0, 1112,
     1112,    0,    0,    0, 1112,   91, 1104,    0,    0,   94,
     1112, 1097,    0,    0,    0, 1112,  105, 1102,    0,  108,
      119, 1093,  210, 1112,  100,  101,  111,  129,  120,   68,
      115,  237,  141,  139,  238,    9,  239,  240,  152,  243,
      249,  258,  113, 1097,    0,    0,    0,  164, 1112,    0,
      275, 1112, 1112,    0,  282, 1112,  270, 1112, 1085, 1068,
      230, 1081,  253, 1069, 1064,  287,  287,  244, 1078, 1068,

     1062,  285, 1079, 1074,  294,  295,  294,  301,  309,  310,
       58,  311,  255,  312,  315,  314,  317,  316,  332,  321,
      329,  331,  324,  325,  335,  338,  340,  343,  342,  345,
      347,  346,  348,  350,  352,  353,  354,  355,  361, 1060,
     1059,  349, 1064, 1069, 1065, 1055, 1071, 1062, 1056, 1060,
     1071, 1052, 1061, 1063, 1047, 1050, 1044, 1043, 1038, 1045,
     1054, 1042, 1054, 1033, 1049, 1037, 1038, 1034, 1041,  362,
      372,  362,  244,  375,  376,  382,  379,  380,  387,  388,
      385,  394,  399,  389,  393,  398,  395,  396,  401,  397,
      407,  413,  412,  417,  414,  419,  420,  426,  425,  427,

      428,  429,  430,  432, 1040, 1030, 1044, 1032,  430, 1044,
     1026, 1027, 1030, 1029, 1018, 1032, 1112, 1019, 1025, 1031,
     1017, 1015, 1028, 1017, 1019, 1023, 1020, 1027, 1016, 1008,
     1020, 1015, 1001, 1013, 1010, 1002, 1015,  431,  436,  442,
      444,  446,  450,  447,  458,  114,  457, 1021,  468,   42,
     1003,  456,  470,  460,  471,  467,  473,  466,  476,  475,
      481,  482,  486,  484,  496,  499,  485,  500,  497,  495,
      493,  505, 1002, 1001, 1004,  996,  998, 1010,  991, 1012,
      985, 1002, 1009, 1008,  996,  985, 1005,  990, 1003,  506,
      997,  979,  996,  980,  981,  978,  988,  995,  994,  989,

      992,  986,  982,  978,  971,  507,  508,  509,  512,  510,
      513,  516,  996, 1112,  526,  528, 1112,  995, 1112,  521,
      969,  534,  993, 1112,  983,  991, 1112, 1112,  527,  532,
      533,  535,  536,  537,  538,  540,  981,  980,  988, 1112,
      987, 1112,  541,  986, 1112,  547,  548,  976,  549,  959,
      958,  968,  964,  966,  954,  955, 1112,  968,  967, 1112,
     1112,  945,  965, 1112,  964, 1112, 1112,  959,  941,  944,
      939,  941,  950,  552,  953,  956, 1112, 1112,  950, 1112,
      940,  953,  952,  927,  560,  564,  558,  559,  562,  563,
      565,  959, 1112,    0, 1112,  949,  941,  575, 1112, 1112,

      568,  569,  571,  576,  581,  574, 1112,  580,  582, 1112,
     1112,  583,  585,  598, 1112,  599,  947,  946,  928,  925,
      926,  935,  920, 1112, 1112,  940, 1112, 1112,  920,  930,
      920,  936,  935,  914, 1112,  911,  911, 1112,  917,  922,
     1112, 1112,  929,  937, 1112,  614, 1112,  591,  601,  596,
      607,  927,  926, 1112,  913,  933,  911,  922,  595,  606,
      912, 1112,  929, 1112,  608,  611,  600,  614,  919,  901,
      926, 1112, 1112, 1112,  891,  915,  889,  913,  912, 1112,
      911,  895,  896, 1112, 1112,  888,  886,  889,  897,  904,
     1112,  624,  627, 1112,  638,  636,  642,  647,  648,  643,

      912, 1112,  645,  657, 1112, 1112,  881,  887, 1112,  658,
      662,  888,  650,  651,  652,  899, 1112,  882,  897, 1112,
      896, 1112, 1112, 1112,  895,  894,  888,  871,  872,  890,
     1112,  666,  675,  676,  678,  682,  898, 1112,  897, 1112,
      867,  874,  877,  893, 1112,  891, 1112,  867,  664,  663,
      879, 1112,  870, 1112, 1112, 1112, 1112,  869,  841,  854,
     1112,  688,  692, 1112, 1112,  693,  829,  820,  695,  826,
      685,  654, 1112,  819,  808,  808, 1112,  697,  699, 1112,
      807,  798,  822, 1112,  812,  706,  709,  790,  808,  805,
      712, 1112,  791,  716, 1112,  747, 1112,  741, 1112,  689,

     1112, 1112,  717,  608,  721,  722,  595, 1112,  594,  727,
     1112,  267,  193,  730,  126,  731,  732,   65,  736, 1112,
      734,  740,  743,  745, 1112, 1112,  752,  762,  772,  782,
      792,  802,  812,    5,  818,  828,  838,  848,  858,  868,
      878,  886
    } ;

static yyconst flex_int16_t yy_def[643] =
    {   0,
      627,  627,  628,  628,  629,  629,  630,  630,  631,  631,
      632,  632,  626,  633,  626,  626,  626,  633,  626,  626,
      626,  626,  626,  626,  626,  634,  634,  626,  635,  626,
      626,  636,  636,  636,  626,  636,  626,  637,  637,  637,
      626,  638,  639,  639,  639,  626,  639,  626,  633,  633,
      626,  640,  626,  626,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  626,  634,  635,  636,  636,  626,  637,
      637,  626,  626,  639,  639,  626,   53,  626,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       87,   87,   87,   87,   87,   87,   87,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  626,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,

      640,  640,  640,  640,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,  626,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      626,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       87,   87,   87,   87,   87,  640,  640,  640,  640,  640,
      640,  640,  626,  626,  640,  640,  626,  626,  626,  640,
      626,  640,  626,  626,  640,  626,  626,  626,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  626,  626,
      626,  626,  640,  626,  626,  640,  640,  640,  640,   87,
       87,   87,   87,   87,   87,   87,  626,   87,   87,  626,
      626,   87,   87,  626,   87,  626,  626,   87,   87,   87,
       87,   87,   87,   87,   87,   87,  626,  626,   87,  626,
       87,   87,   87,   87,  640,  640,  640,  640,  640,  640,
      640,  626,  626,  641,  626,  640,  626,  626,  626,  626,

      640,  640,  640,  640,  640,  640,  626,  640,  640,  626,
      626,  640,  640,  626,  626,  640,   87,   87,   87,   87,
       87,   87,   87,  626,  626,   87,  626,  626,   87,   87,
       87,   87,   87,   87,  626,   87,   87,  626,   87,   87,
      626,  626,   87,  626,  626,  642,  626,  640,  640,  640,
      640,  640,  641,  626,  626,  626,  626,  640,  640,  640,
      626,  626,  626,  626,  640,  640,  640,  640,  640,  626,
      626,  626,  626,  626,   87,   87,   87,   87,   87,  626,
       87,   87,   87,  626,  626,   87,   87,   87,   87,   87,
      626,  642,  642,  626,  642,  642,  642,  642,  642,  640,

      626,  626,  640,  626,  626,  626,  626,  626,  626,  640,
      640,  626,  640,  640,  640,  640,  626,  626,   87,  626,
       87,  626,  626,  626,   87,   87,   87,   87,   87,   87,
      626,  642,  642,  642,  642,  642,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  640,  640,
      640,  626,  626,  626,  626,  626,  626,   87,   87,   87,
      626,  642,  642,  626,  626,  642,  626,  626,  626,  626,
      640,  640,  626,  626,   87,   87,  626,  642,  642,  626,
      626,  626,  626,  626,  626,  640,  640,  626,   87,   87,
      642,  626,  626,  626,  626,  626,  626,  626,  626,  626,

      626,  626,  642,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,    0,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626
    } ;

static yyconst flex_int16_t yy_nxt[1152] =
    {   0,
      626,   15,   16,   15,   17,   18,   50,   51,   50,   75,
       19,  626,   20,   15,   16,   15,   17,   18,   51,   51,
       51,   54,   19,  626,   20,   21,   15,   16,   15,   22,
       23,   24,   25,   26,   24,   24,   24,   24,  125,   21,
       21,   21,   15,   16,   15,   22,   23,   24,   25,   26,
       24,   24,   24,   24,   54,   21,   21,   21,   15,   16,
       15,   28,   23,   21,   21,  320,   21,   21,   30,   31,
       54,   21,   21,   15,   16,   15,   28,   23,   21,   21,
       54,   21,   21,   30,   31,  175,   21,   33,   34,   33,
       35,   36,   78,   78,   78,   81,   51,   81,  621,  115,

       37,   33,   34,   33,   35,   36,   85,   85,   85,   50,
       51,   50,   54,   54,   37,   39,   16,   39,  108,   40,
       51,   51,   51,   54,   41,   54,   54,   54,   42,   39,
       16,   39,   54,   40,  110,  109,  138,  139,   41,  113,
      111,   54,   42,   44,   45,   44,   46,   47,  114,  112,
      116,   54,  315,   54,  618,  122,   48,   44,   45,   44,
       46,   47,  119,  123,   54,   78,   78,   78,  129,  120,
       48,   52,   52,   52,  121,   52,   52,   52,   52,   52,
       53,   52,   52,   54,   52,   52,   52,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   52,   64,   65,   66,

       67,   68,   69,   70,   71,   52,   72,   73,   52,   52,
       87,   87,   87,  615,   87,   87,   87,   87,   87,   87,
       87,   87,   88,   87,   87,   87,   89,   90,   91,   92,
       93,   94,   95,   96,   97,   87,   98,   99,  100,  101,
      102,  103,  104,  105,   87,  106,  107,   87,   87,   54,
       54,   54,   54,  142,  117,   54,   54,  118,  124,  143,
      154,   54,  240,  130,  127,  132,  131,   54,  155,  133,
       54,  128,  145,  126,  135,  136,   81,   51,   81,  177,
      134,  146,  137,   85,   85,   85,   87,   87,   87,   87,
       87,   87,   87,   87,   87,  614,   87,   87,   87,   87,

       87,   87,   87,   87,  149,   87,   87,  150,  151,  159,
      163,  166,  167,   54,  164,  152,  160,  169,  170,  168,
      153,   54,   54,   54,   54,  165,   54,   54,   54,   54,
      173,  179,  176,   54,  171,  183,   54,   54,  180,  174,
      182,   54,  172,   54,   54,  178,  181,   54,  186,  185,
       54,  184,   54,  188,   54,   54,  187,   54,   54,   54,
       54,  193,   54,  196,   54,   54,   54,   54,  189,  207,
      198,  190,  192,   54,   54,  194,  195,  191,  208,  202,
      203,  236,  200,  199,   54,  197,  201,   54,   54,  204,
      237,   54,   54,  242,   54,  239,  238,   54,  244,   54,

       54,   54,  183,  243,  241,   54,   54,   54,   54,   54,
       54,  246,  245,   54,  247,  248,  250,  251,  254,   54,
      253,  257,  249,  252,   54,   54,   54,  258,  255,   54,
      256,   54,   54,  262,  259,  260,  261,   54,   54,   54,
       54,   54,   54,   54,   54,  264,  266,  277,   54,  267,
      263,  272,  269,  265,   54,  270,   54,  278,   54,   54,
      306,  313,   54,  271,  268,  307,  311,  308,   54,   54,
      314,  318,   54,  323,  326,  310,  309,  316,   54,  328,
      319,  312,  324,  327,  329,   54,  325,   54,   54,  322,
      331,  330,  333,   54,   54,  337,   54,   54,   54,  339,

      332,  343,  341,  344,  338,   54,  334,   54,  340,   54,
      335,  342,  345,  336,  346,  347,  348,   54,  367,   54,
       54,   54,   54,  368,   54,   54,  387,  389,   54,  392,
      369,  394,  388,   54,  349,  385,  386,  398,  393,   54,
      395,  390,  391,  401,   54,   54,  399,   54,   54,   54,
      407,  414,   54,   54,  396,  408,  409,  406,  412,   54,
       54,   54,  403,  444,  435,  402,  405,  446,  404,  436,
       54,   54,  445,  413,   54,   54,  447,   54,  456,  461,
       54,   54,  451,   54,  463,  416,   54,  448,  462,  459,
      449,  450,   54,  464,   54,   54,  457,   54,  452,  458,

      460,  414,  471,   54,  501,  469,  465,   54,   54,  468,
      504,  472,   54,  502,  466,  467,  470,  492,   54,   54,
       54,  613,  510,   54,  612,  494,   54,  492,  500,  515,
      626,  511,  495,  503,  516,  494,  609,  496,  494,  626,
      513,  626,  497,  498,  514,  626,  537,  494,  539,  494,
      626,  626,  499,  494,  532,  538,  533,  540,  494,  494,
      504,  544,   54,   54,   54,  546,   54,  549,  536,  626,
      545,  534,  535,  541,  547,   54,   54,  494,  626,  626,
      571,  626,  587,  551,  550,  626,  494,  494,  564,  494,
      565,  626,  572,  494,  562,  626,  626,   54,  583,  494,

      626,  563,  626,  494,  494,  580,  578,  584,  494,  596,
      494,  592,  598,  607,  566,  626,  586,  591,  597,  605,
      626,  599,  579,  494,  605,  610,  611,  606,  494,  608,
      610,  611,  606,  616,  616,  619,  620,  622,  603,  619,
      620,  617,  617,  622,  598,  623,  624,  625,  624,  625,
      596,  623,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   38,   38,   38,   38,   38,   38,   38,   38,

       38,   38,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   49,  604,   49,   49,   49,  602,   49,   49,
      601,   49,   76,  600,  595,  583,  594,   76,   77,   77,
       77,  593,   77,   77,   77,   77,  590,   77,   80,  589,
       80,   80,   80,  588,   80,   80,  585,   80,   82,  582,
       82,   82,   82,   82,   82,   82,   82,   82,   84,   84,
       84,  581,   84,   84,   84,   84,  577,   84,   52,   52,
      576,   52,   52,   52,   52,   52,   52,   52,  453,  453,
      453,  453,  453,  453,  453,  575,  453,  453,  493,  574,
      493,  573,  493,  570,  546,  493,  544,  569,  568,  567,

      539,  537,  561,  560,  559,  558,  557,  556,  555,  554,
      553,  552,  548,  543,  542,  501,  531,  530,  529,  528,
      527,  526,  525,  524,  523,  522,  521,  520,  519,  471,
      518,  517,  463,  512,  509,  508,  456,  507,  506,  505,
      444,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      455,  454,  392,  443,  442,  441,  440,  439,  438,  437,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  415,  344,
      341,  339,  411,  410,  326,  400,  323,  397,  318,  313,

      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  366,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  321,  317,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  276,  275,  274,  273,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  206,  205,  162,  161,  158,  157,  156,  148,

      147,  144,  141,  140,   74,   54,   86,   83,   79,   74,
      626,   13,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626
    } ;

static yyconst flex_int16_t yy_chk[1152] =
    {   0,
        0,    1,    1,    1,    1,    1,   18,   18,   18,  634,
        1,    0,    1,    2,    2,    2,    2,    2,   23,   23,
       23,   66,    2,    0,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   66,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,  250,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,  250,    5,    5,    5,    5,
      111,    5,    6,    6,    6,    6,    6,    6,    6,    6,
       60,    6,    6,    6,    6,  111,    6,    7,    7,    7,
        7,    7,   36,   36,   36,   40,   40,   40,  618,   60,

        7,    8,    8,    8,    8,    8,   47,   47,   47,   50,
       50,   50,   55,   56,    8,    9,    9,    9,   55,    9,
       51,   51,   51,   57,    9,   73,  246,   61,    9,   10,
       10,   10,   59,   10,   57,   56,   73,   73,   10,   59,
       57,   58,   10,   11,   11,   11,   11,   11,   59,   58,
       61,   64,  246,   63,  615,   64,   11,   12,   12,   12,
       12,   12,   63,   64,   69,   78,   78,   78,   69,   63,
       12,   19,   19,   19,   63,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       53,   53,   53,  613,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   62,
       65,   67,   68,   91,   62,   70,  173,   62,   65,   91,
       98,   71,  173,   70,   68,   71,   70,  113,   98,   71,
       72,   68,   93,   67,   72,   72,   81,   81,   81,  113,
       71,   93,   72,   85,   85,   85,   87,   87,   87,   87,
       87,   87,   87,   87,   87,  612,   87,   87,   87,   87,

       87,   87,   87,   87,   96,   87,   87,   96,   97,  102,
      105,  106,  106,  108,  105,   97,  102,  107,  107,  106,
       97,  109,  110,  112,  114,  105,  116,  115,  118,  117,
      110,  115,  112,  120,  108,  119,  123,  124,  116,  110,
      118,  121,  109,  122,  119,  114,  117,  125,  122,  121,
      126,  120,  127,  124,  129,  128,  123,  130,  132,  131,
      133,  129,  134,  132,  135,  136,  137,  138,  125,  142,
      134,  126,  128,  139,  172,  130,  131,  127,  142,  138,
      139,  170,  136,  135,  171,  133,  137,  174,  175,  139,
      170,  177,  178,  175,  176,  172,  171,  181,  176,  179,

      180,  184,  183,  175,  174,  185,  182,  187,  188,  190,
      186,  178,  177,  189,  179,  180,  182,  183,  186,  191,
      185,  189,  181,  184,  193,  192,  195,  190,  187,  194,
      188,  196,  197,  194,  191,  192,  193,  199,  198,  200,
      201,  202,  203,  238,  204,  196,  198,  209,  239,  199,
      195,  204,  201,  197,  240,  202,  241,  209,  242,  244,
      238,  245,  243,  203,  200,  239,  243,  240,  252,  247,
      245,  249,  254,  253,  255,  242,  241,  247,  258,  256,
      249,  244,  253,  255,  256,  257,  254,  260,  259,  252,
      257,  256,  259,  261,  262,  263,  264,  267,  263,  265,

      258,  267,  266,  268,  264,  271,  260,  270,  265,  269,
      261,  266,  268,  262,  269,  270,  271,  272,  290,  306,
      307,  308,  310,  290,  309,  311,  308,  310,  312,  315,
      290,  316,  309,  320,  272,  306,  307,  322,  315,  329,
      316,  311,  312,  329,  330,  331,  322,  332,  333,  334,
      335,  347,  336,  343,  320,  335,  336,  334,  343,  346,
      347,  349,  331,  385,  374,  330,  333,  386,  332,  374,
      387,  388,  385,  346,  389,  390,  386,  391,  398,  404,
      401,  402,  390,  403,  405,  349,  406,  387,  404,  402,
      388,  389,  408,  405,  409,  412,  398,  413,  391,  401,

      403,  414,  416,  448,  449,  413,  406,  459,  450,  412,
      451,  416,  467,  449,  408,  409,  414,  446,  460,  451,
      465,  609,  459,  466,  607,  446,  468,  492,  448,  467,
      493,  460,  446,  450,  468,  492,  604,  446,  493,  496,
      465,  495,  446,  446,  466,  497,  500,  496,  503,  495,
      498,  499,  446,  497,  495,  500,  496,  503,  498,  499,
      504,  510,  513,  514,  515,  511,  572,  513,  499,  532,
      510,  497,  498,  504,  511,  550,  549,  532,  533,  534,
      549,  535,  572,  515,  514,  536,  533,  534,  534,  535,
      535,  562,  550,  536,  532,  563,  566,  571,  569,  562,

      578,  533,  579,  563,  566,  566,  562,  569,  578,  586,
      579,  579,  587,  600,  536,  591,  571,  578,  586,  594,
      603,  587,  563,  591,  605,  606,  606,  594,  603,  603,
      610,  610,  605,  614,  616,  617,  617,  621,  591,  619,
      619,  614,  616,  622,  598,  621,  623,  623,  624,  624,
      596,  622,  627,  627,  627,  627,  627,  627,  627,  627,
      627,  627,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  629,  629,  629,  629,  629,  629,  629,  629,
      629,  629,  630,  630,  630,  630,  630,  630,  630,  630,
      630,  630,  631,  631,  631,  631,  631,  631,  631,  631,

      631,  631,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  633,  593,  633,  633,  633,  590,  633,  633,
      589,  633,  635,  588,  585,  583,  582,  635,  636,  636,
      636,  581,  636,  636,  636,  636,  576,  636,  637,  575,
      637,  637,  637,  574,  637,  637,  570,  637,  638,  568,
      638,  638,  638,  638,  638,  638,  638,  638,  639,  639,
      639,  567,  639,  639,  639,  639,  560,  639,  640,  640,
      559,  640,  640,  640,  640,  640,  640,  640,  641,  641,
      641,  641,  641,  641,  641,  558,  641,  641,  642,  553,
      642,  551,  642,  548,  546,  642,  544,  543,  542,  541,

      539,  537,  530,  529,  528,  527,  526,  525,  521,  519,
      518,  516,  512,  508,  507,  501,  490,  489,  488,  487,
      486,  483,  482,  481,  479,  478,  477,  476,  475,  471,
      470,  469,  463,  461,  458,  457,  456,  455,  453,  452,
      444,  443,  440,  439,  437,  436,  434,  433,  432,  431,
      430,  429,  426,  423,  422,  421,  420,  419,  418,  417,
      397,  396,  392,  384,  383,  382,  381,  379,  376,  375,
      373,  372,  371,  370,  369,  368,  365,  363,  362,  359,
      358,  356,  355,  354,  353,  352,  351,  350,  348,  344,
      341,  339,  338,  337,  326,  325,  323,  321,  318,  313,

      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  251,  248,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  216,  215,  214,  213,  212,  211,
      210,  208,  207,  206,  205,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  141,  140,  104,  103,  101,  100,   99,   95,

       94,   92,   90,   89,   74,   52,   48,   42,   37,   25,
       13,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626
    } ;

extern int gtkdialog__flex_debug;
int gtkdialog__flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up gtkdialog_text */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *gtkdialog_text;
#line 1 "gtkdialog_lexer.l"
#line 2 "gtkdialog_lexer.l"
/*
** $Id: lexer.l,v 1.2 2004/11/20 20:01:25 root Exp root $
** $Log: lexer.l,v $
** Revision 1.2  2004/11/20 20:01:25  root
** - Log entries.
**
*/
#define YY_INPUT(buf,result,max_size) \
    { \
    int c = getnextchar(); \
    result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
    }


#include <string.h>
#include <gtk/gtk.h>

#include "gtkdialog.h"
#include "attributes.h"
#include "gtkdialog_parser.h"

static gchar *process_string(gchar *str);

extern int linenumber;
gchar *Token;




#line 1028 "gtkdialog_lexer.c"

#define INITIAL 0
#define EMBEDDED 1
#define ST_TAG_ATTR 2
#define ST_QUOTED_TAGATTR 3
#define ST_STRING 4
#define ST_QUOTED_STRING 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int gtkdialog_lex_destroy (void );

int gtkdialog_get_debug (void );

void gtkdialog_set_debug (int debug_flag  );

YY_EXTRA_TYPE gtkdialog_get_extra (void );

void gtkdialog_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *gtkdialog_get_in (void );

void gtkdialog_set_in  (FILE * in_str  );

FILE *gtkdialog_get_out (void );

void gtkdialog_set_out  (FILE * out_str  );

int gtkdialog_get_leng (void );

char *gtkdialog_get_text (void );

int gtkdialog_get_lineno (void );

void gtkdialog_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int gtkdialog_wrap (void );
#else
extern int gtkdialog_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( gtkdialog_text, gtkdialog_leng, 1, gtkdialog_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( gtkdialog_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( gtkdialog_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, gtkdialog_in))==0 && ferror(gtkdialog_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(gtkdialog_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int gtkdialog_lex (void);

#define YY_DECL int gtkdialog_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after gtkdialog_text and gtkdialog_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 34 "gtkdialog_lexer.l"


	#ifdef DEBUG
		g_message("%s(): Start", __func__);
	#endif

#line 1227 "gtkdialog_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)gtkdialog_alloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in gtkdialog_lex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! gtkdialog_in )
			gtkdialog_in = stdin;

		if ( ! gtkdialog_out )
			gtkdialog_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			gtkdialog_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE );
		}

		gtkdialog__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of gtkdialog_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 627 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1112 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 40 "gtkdialog_lexer.l"
{ Token=">"; return(gtkdialog_text[0]); 			}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "gtkdialog_lexer.l"
{ Token="indent chars"; 				}
	YY_BREAK
/*
	 * Attributes.
	 */
case 3:
YY_RULE_SETUP
#line 46 "gtkdialog_lexer.l"
{
	#ifdef DEBUG 
	g_message(" -> TAG_ATTR_NAME: '%s'", gtkdialog_text);
	#endif
	Token="tag attribute name";
	gtkdialog_lval.cval=strdup(gtkdialog_text);
	return TAG_ATTR_NAME;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "gtkdialog_lexer.l"
{
					  #ifdef DEBUG 
					  g_message(" -> spec char: '%s'", gtkdialog_text);
					  #endif
					  Token="=";
					  return '=';
												}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "gtkdialog_lexer.l"
{
					  #ifdef DEBUG 
					  g_message(" -> spec char: '%s'", gtkdialog_text);
					  #endif
					  Token=">";
					  BEGIN(0);
					  return '>';
												}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "gtkdialog_lexer.l"
{
					  Token = "double quote";
					  BEGIN(ST_QUOTED_TAGATTR);				}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 76 "gtkdialog_lexer.l"
{
					  Token = "string";
					  yymore();						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "gtkdialog_lexer.l"
{
					  Token = "string";
					  yymore();						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "gtkdialog_lexer.l"
{
					  Token = gtkdialog_text;
					  gtkdialog_lval.cval = g_strdup(gtkdialog_text);
					  gtkdialog_lval.cval[strlen(gtkdialog_lval.cval) - 1] = '\0';
					  BEGIN(ST_TAG_ATTR);
					  return STRING;
					  							}
	YY_BREAK
/*
	 * The elements of the embedded imperative language.
	 */
case 10:
YY_RULE_SETUP
#line 100 "gtkdialog_lexer.l"
{ 
	Token="<show/>"; 
	return SHOW_WIDGETS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 105 "gtkdialog_lexer.l"
{
	Token="<command>";    
	BEGIN(EMBEDDED);
	return COMM;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "gtkdialog_lexer.l"
{
	Token="<if>";    
	BEGIN(EMBEDDED);
	return IF;           
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 117 "gtkdialog_lexer.l"
{
	Token="<while>";    
	BEGIN(EMBEDDED);
	return WHILE;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 123 "gtkdialog_lexer.l"
{
	Token = "operator";
	return gtkdialog_text[0];
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 128 "gtkdialog_lexer.l"
{
	Token = "variable";
	gtkdialog_lval.cval = g_strdup(gtkdialog_text);
	return EMB_VARIABLE;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "gtkdialog_lexer.l"
{
	Token = "number";
	gtkdialog_lval.cval = g_strdup(gtkdialog_text);
	return EMB_NUMBER;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 140 "gtkdialog_lexer.l"
{ 
	BEGIN(0);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 144 "gtkdialog_lexer.l"
{ 
	Token="</if>"; 
	return ENDCOMM;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 149 "gtkdialog_lexer.l"
{ 
	Token="</if>"; 
	return ENDIF;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 154 "gtkdialog_lexer.l"
{ 
	Token="</while>"; 
	return EWHILE;
}
	YY_BREAK
/*
	 * The widget tags.
	 */
case 21:
YY_RULE_SETUP
#line 163 "gtkdialog_lexer.l"
{ 
	Token="<window>"; 
	return(WINDOW);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "gtkdialog_lexer.l"
{ 
	Token="<window>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_WINDOW);  		
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 174 "gtkdialog_lexer.l"
{ 
	Token="</window>"; 
	return(EWINDOW);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 180 "gtkdialog_lexer.l"
{ 
	Token="<notebook>"; 
	return(NOTEBOOK);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 185 "gtkdialog_lexer.l"
{ 
	Token="</notebook>"; 
	return(ENOTEBOOK);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 190 "gtkdialog_lexer.l"
{ 
	Token="<notebook>";
	BEGIN(ST_TAG_ATTR);
	return(PART_NOTEBOOK);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 197 "gtkdialog_lexer.l"
{ 
	Token="<vbox>"; 
	return(VBOX);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 202 "gtkdialog_lexer.l"
{ 
	Token="<hbox>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_VBOX);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 208 "gtkdialog_lexer.l"
{ 
	Token="</vbox>"; 
	return(EVBOX);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 214 "gtkdialog_lexer.l"
{ 
	Token="<hbox>"; 
	return(HBOX);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 219 "gtkdialog_lexer.l"
{ 
	Token="<hbox>";
	BEGIN(ST_TAG_ATTR);
	return(PART_HBOX);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 225 "gtkdialog_lexer.l"
{ 
	Token="</hbox>"; 
	return(EHBOX);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 231 "gtkdialog_lexer.l"
{ 
	Token="<frame>"; 
	gtkdialog_lval.cval = "";  
	return(FRAME); 	
}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 237 "gtkdialog_lexer.l"
{
	Token="<frame>";
	gtkdialog_lval.cval=strdup(&gtkdialog_text[7]);  
	gtkdialog_lval.cval[strlen(gtkdialog_lval.cval)-1] = 0;
	return FRAME; 
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 244 "gtkdialog_lexer.l"
{ 
	Token="</frame>"; 
	return(EFRAME);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 250 "gtkdialog_lexer.l"
{ 
	Token="<text>"; 
	return(TEXT);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 255 "gtkdialog_lexer.l"
{ 
	Token="<text>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_TEXT);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 261 "gtkdialog_lexer.l"
{ 
	Token="</text>"; 
	return(ETEXT);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 267 "gtkdialog_lexer.l"
{ 
	Token="<pixmap>"; 
	return(PIXMAP);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 272 "gtkdialog_lexer.l"
{ 
	Token="</pixmap>"; 
	return(EPIXMAP); 
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 277 "gtkdialog_lexer.l"
{ 
	Token="<pixmap>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_PIXMAP);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 284 "gtkdialog_lexer.l"
{ 
	Token="<entry>"; 
	return(ENTRY);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 289 "gtkdialog_lexer.l"
{ 
	Token="</entry>"; 
	return(EENTRY);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 294 "gtkdialog_lexer.l"
{ 
	Token="<entry>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_ENTRY);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 301 "gtkdialog_lexer.l"
{ 
	Token="<edit>"; 
	return(EDIT);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 306 "gtkdialog_lexer.l"
{ 
	Token="<entry>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_EDIT);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 312 "gtkdialog_lexer.l"
{ 
	Token="</edit>"; 
	return(EEDIT);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 318 "gtkdialog_lexer.l"
{ 
	Token="<tree>";  
	return  TREE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 323 "gtkdialog_lexer.l"
{ 
	Token="<tree>";  
	BEGIN(ST_TAG_ATTR);
	return PART_TREE;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 329 "gtkdialog_lexer.l"
{
	Token="</tree>"; 
	return ETREE;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 335 "gtkdialog_lexer.l"
{ 
	Token="<chooser>"; 
	return(CHOOSER);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 340 "gtkdialog_lexer.l"
{ 
	Token="</chooser>"; 
	return(ECHOOSER);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 345 "gtkdialog_lexer.l"
{ 
	Token="<chooser>";  
	BEGIN(ST_TAG_ATTR);
	return PART_CHOOSER;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 352 "gtkdialog_lexer.l"
{ 
	Token="<button>"; 
	return(BUTTON);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 357 "gtkdialog_lexer.l"
{ 
	Token="</button>"; 
	return(EBUTTON);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 362 "gtkdialog_lexer.l"
{ 
	//g_message("PART_BUTTON: '%s'", gtkdialog_text);
	Token="<button>";  
	BEGIN(ST_TAG_ATTR);
	return PART_BUTTON;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 369 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONOK);  			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 370 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONCANCEL);  		}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 371 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONHELP);  		}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 372 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONYES);  		}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 373 "gtkdialog_lexer.l"
{ Token="<button>"; return(BUTTONNO);  			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 375 "gtkdialog_lexer.l"
{ Token="<checkbox>"; return(CHECKBOX);       		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 376 "gtkdialog_lexer.l"
{ Token="</checkbox>"; return(ECHECKBOX);     		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 377 "gtkdialog_lexer.l"
{ Token="<chackbox>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_CHECKBOX);  				}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 381 "gtkdialog_lexer.l"
{ Token="<radiobutton>"; return(RADIO);      		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 382 "gtkdialog_lexer.l"
{ Token="</radiobutton>"; return(ERADIO);    		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 383 "gtkdialog_lexer.l"
{ Token="<radiobutton>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_RADIO);  					}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 387 "gtkdialog_lexer.l"
{ Token="<progressbar>"; return(PROGRESS);      	}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 388 "gtkdialog_lexer.l"
{ Token="</progressbar>"; return(EPROGRESS);    	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 389 "gtkdialog_lexer.l"
{ Token="<progressbar>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_PROGRESS);  				}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 394 "gtkdialog_lexer.l"
{ Token="<radio>"; return(RADIO);  			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 395 "gtkdialog_lexer.l"
{ Token="</radio>"; return(ERADIO);  			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 397 "gtkdialog_lexer.l"
{ Token="<gvim>"; return(GVIM);  			}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 398 "gtkdialog_lexer.l"
{ Token="</gvim>"; return(EGVIM);  			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 400 "gtkdialog_lexer.l"
{ Token="<combobox>"; return(COMBO);  	  		}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 401 "gtkdialog_lexer.l"
{ Token="<combobox>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_COMBO); 					}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 404 "gtkdialog_lexer.l"
{ Token="</combobox>"; return(ECOMBO);    		}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 406 "gtkdialog_lexer.l"
{ Token="<list>";  return(LIST);  			}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 407 "gtkdialog_lexer.l"
{ Token="<list>";  
					  BEGIN(ST_TAG_ATTR);
					  return(PART_LIST); 					}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 410 "gtkdialog_lexer.l"
{ Token="</list>"; return(ELIST);  			}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 412 "gtkdialog_lexer.l"
{ Token="<table>"; return(TABLE);  			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 413 "gtkdialog_lexer.l"
{ Token="</table>"; return(ETABLE);  			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 415 "gtkdialog_lexer.l"
{ Token="<menubar>"; return(MENUBAR);  			}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 416 "gtkdialog_lexer.l"
{ Token="</menubar>"; return(EMENUBAR);			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 418 "gtkdialog_lexer.l"
{ Token="<menu>"; return(MENU);  			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 419 "gtkdialog_lexer.l"
{ Token="</menu>"; return(EMENU);			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 421 "gtkdialog_lexer.l"
{ Token="<menuitem>"; return(MENUITEM);  		}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 422 "gtkdialog_lexer.l"
{ Token="<menuitem>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_MENUITEM);  				}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 425 "gtkdialog_lexer.l"
{ Token="</menuitem>"; return(EMENUITEM);		}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 427 "gtkdialog_lexer.l"
{ Token="<separator>"; return(SEPARATOR);  		}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 428 "gtkdialog_lexer.l"
{ Token="</separator>"; return(ESEPARATOR);		}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 438 "gtkdialog_lexer.l"
{ Token="<label>"; return(LABEL);    			}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 439 "gtkdialog_lexer.l"
{ Token="</label>"; return(ELABEL);  			}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 441 "gtkdialog_lexer.l"
{ Token="<item>"; return(ITEM);      			}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 442 "gtkdialog_lexer.l"
{ Token="</item>"; return(EITEM);    			}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 443 "gtkdialog_lexer.l"
{ Token="<item>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_ITEM); 					}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 447 "gtkdialog_lexer.l"
{ Token="<default>"; return(DEFAULT);  			}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 448 "gtkdialog_lexer.l"
{ Token="</default>"; return(EDEFAULT);  		}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 450 "gtkdialog_lexer.l"
{ Token="<visible>"; return(VISIBLE);  			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 451 "gtkdialog_lexer.l"
{ Token="</visible>"; return(EVISIBLE);  		}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 453 "gtkdialog_lexer.l"
{ 
					  Token="<variable>"; 
					  return(VARIABLE); 					}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 456 "gtkdialog_lexer.l"
{ 
					  Token="</variable>"; 
					  return(EVARIABLE); 					}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 460 "gtkdialog_lexer.l"
{ Token="<height>"; return(HEIGHT);  			}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 461 "gtkdialog_lexer.l"
{ Token="</height>"; return(EHEIGHT);  			}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 463 "gtkdialog_lexer.l"
{ Token="<width>"; return(WIDTH);   			}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 464 "gtkdialog_lexer.l"
{ Token="</width>"; return(EWIDTH);   			}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 466 "gtkdialog_lexer.l"
{ Token="<input>"; return(INPUT);   			}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 467 "gtkdialog_lexer.l"
{ Token="</input>"; return(EINPUT);   			}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 468 "gtkdialog_lexer.l"
{ Token="<input file>"; return(INPUTFILE);   		}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 469 "gtkdialog_lexer.l"
{ Token="<input file>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_INPUTFILE);   				}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 472 "gtkdialog_lexer.l"
{ Token="<input>"; 
					  BEGIN(ST_TAG_ATTR);
					  return(PART_INPUT);   				}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 476 "gtkdialog_lexer.l"
{ Token="<output>"; return(OUTPUT);   			}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 477 "gtkdialog_lexer.l"
{ Token="</output>"; return(EOUTPUT);   		}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 478 "gtkdialog_lexer.l"
{ Token="<output>"; return(OUTPUTFILE);   		}
	YY_BREAK
/*
	** The definition of action tags.
	*/
case 115:
YY_RULE_SETUP
#line 483 "gtkdialog_lexer.l"
{ 
	Token="<action>"; 
	return(ACTION);
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 488 "gtkdialog_lexer.l"
{ 
	Token="<action>"; 
	BEGIN(ST_TAG_ATTR);
	return(PART_ACTION);
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 494 "gtkdialog_lexer.l"
{ 
	Token="</action>"; 
	return(EACTION);
}
	YY_BREAK
case 118:
/* rule 118 can match eol */
YY_RULE_SETUP
#line 504 "gtkdialog_lexer.l"
{ 
	Token=g_strdup(gtkdialog_text); 
	gtkdialog_error("Unknown end tag.");  
}
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 509 "gtkdialog_lexer.l"
{ 
	Token=g_strdup(gtkdialog_text); 
	gtkdialog_error("Unknown tag.");      
}
	YY_BREAK
/*
					 * The quoted string. It can contain anything, except
					 * unescaped double quote.
					 */
case 120:
YY_RULE_SETUP
#line 518 "gtkdialog_lexer.l"
{
					  Token = "double quote";
					  BEGIN(ST_QUOTED_STRING);				}
	YY_BREAK
case 121:
/* rule 121 can match eol */
YY_RULE_SETUP
#line 522 "gtkdialog_lexer.l"
{
					  yymore();						}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 525 "gtkdialog_lexer.l"
{
					  yymore();						}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 528 "gtkdialog_lexer.l"
{
					  Token = gtkdialog_text;
					  gtkdialog_lval.cval = g_strdup(gtkdialog_text);
					  gtkdialog_lval.cval[strlen(gtkdialog_lval.cval) - 1] = '\0';
					  BEGIN(0);
					  return STRING;
					  							}
	YY_BREAK
/*
					 * An unquoted string can contain anything except 
					 * unescaped '<'.
					 */
case 124:
YY_RULE_SETUP
#line 540 "gtkdialog_lexer.l"
{
					  Token = "string";
					  BEGIN(ST_STRING);
					  yymore();
												}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 545 "gtkdialog_lexer.l"
{
					  Token = "string";
					  yymore();
												}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 551 "gtkdialog_lexer.l"
{
					  yymore();
												}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 555 "gtkdialog_lexer.l"
{
					  yymore();
												}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 559 "gtkdialog_lexer.l"
{
					  gtkdialog_lval.cval = g_strdup(gtkdialog_text);
					  gtkdialog_lval.cval[strlen(gtkdialog_lval.cval) - 1] = '\0';
					  unput('<');
					  BEGIN(0);
					  return STRING;
					  							}
	YY_BREAK
case 129:
/* rule 129 can match eol */
YY_RULE_SETUP
#line 569 "gtkdialog_lexer.l"
{
					  ++linenumber;
												}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 572 "gtkdialog_lexer.l"
{
					  /* */
												}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 576 "gtkdialog_lexer.l"
{
					  /* we do nothing, this is a dropped char. */
												}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 579 "gtkdialog_lexer.l"
ECHO;
	YY_BREAK
#line 2295 "gtkdialog_lexer.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(EMBEDDED):
			case YY_STATE_EOF(ST_TAG_ATTR):
			case YY_STATE_EOF(ST_QUOTED_TAGATTR):
			case YY_STATE_EOF(ST_STRING):
			case YY_STATE_EOF(ST_QUOTED_STRING):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed gtkdialog_in at a new source and called
			 * gtkdialog_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = gtkdialog_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( gtkdialog_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * gtkdialog_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of gtkdialog_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			gtkdialog_restart(gtkdialog_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) gtkdialog_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 627 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 627 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 626);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up gtkdialog_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					gtkdialog_restart(gtkdialog_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( gtkdialog_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve gtkdialog_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void gtkdialog_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        gtkdialog_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            gtkdialog__create_buffer(gtkdialog_in,YY_BUF_SIZE );
	}

	gtkdialog__init_buffer(YY_CURRENT_BUFFER,input_file );
	gtkdialog__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void gtkdialog__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		gtkdialog_pop_buffer_state();
	 *		gtkdialog_push_buffer_state(new_buffer);
     */
	gtkdialog_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	gtkdialog__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (gtkdialog_wrap()) processing, but the only time this flag
	 * is looked at is after gtkdialog_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void gtkdialog__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	gtkdialog_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE gtkdialog__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) gtkdialog_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) gtkdialog_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__create_buffer()" );

	b->yy_is_our_buffer = 1;

	gtkdialog__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with gtkdialog__create_buffer()
 * 
 */
    void gtkdialog__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		gtkdialog_free((void *) b->yy_ch_buf  );

	gtkdialog_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a gtkdialog_restart() or at EOF.
 */
    static void gtkdialog__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	gtkdialog__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then gtkdialog__init_buffer was _probably_
     * called from gtkdialog_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void gtkdialog__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		gtkdialog__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void gtkdialog_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	gtkdialog_ensure_buffer_stack();

	/* This block is copied from gtkdialog__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from gtkdialog__switch_to_buffer. */
	gtkdialog__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void gtkdialog_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	gtkdialog__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		gtkdialog__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void gtkdialog_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)gtkdialog_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gtkdialog_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)gtkdialog_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gtkdialog_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE gtkdialog__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) gtkdialog_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	gtkdialog__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to gtkdialog_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       gtkdialog__scan_bytes() instead.
 */
YY_BUFFER_STATE gtkdialog__scan_string (yyconst char * yystr )
{
    
	return gtkdialog__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to gtkdialog_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE gtkdialog__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) gtkdialog_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in gtkdialog__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = gtkdialog__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in gtkdialog__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gtkdialog_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		gtkdialog_text[gtkdialog_leng] = (yy_hold_char); \
		(yy_c_buf_p) = gtkdialog_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		gtkdialog_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int gtkdialog_get_lineno  (void)
{
        
    return gtkdialog_lineno;
}

/** Get the input stream.
 * 
 */
FILE *gtkdialog_get_in  (void)
{
        return gtkdialog_in;
}

/** Get the output stream.
 * 
 */
FILE *gtkdialog_get_out  (void)
{
        return gtkdialog_out;
}

/** Get the length of the current token.
 * 
 */
int gtkdialog_get_leng  (void)
{
        return gtkdialog_leng;
}

/** Get the current token.
 * 
 */

char *gtkdialog_get_text  (void)
{
        return gtkdialog_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void gtkdialog_set_lineno (int  line_number )
{
    
    gtkdialog_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see gtkdialog__switch_to_buffer
 */
void gtkdialog_set_in (FILE *  in_str )
{
        gtkdialog_in = in_str ;
}

void gtkdialog_set_out (FILE *  out_str )
{
        gtkdialog_out = out_str ;
}

int gtkdialog_get_debug  (void)
{
        return gtkdialog__flex_debug;
}

void gtkdialog_set_debug (int  bdebug )
{
        gtkdialog__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from gtkdialog_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    gtkdialog_in = stdin;
    gtkdialog_out = stdout;
#else
    gtkdialog_in = (FILE *) 0;
    gtkdialog_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * gtkdialog_lex_init()
     */
    return 0;
}

/* gtkdialog_lex_destroy is for both reentrant and non-reentrant scanners. */
int gtkdialog_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		gtkdialog__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		gtkdialog_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	gtkdialog_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    gtkdialog_free ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * gtkdialog_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *gtkdialog_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *gtkdialog_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void gtkdialog_free (void * ptr )
{
	free( (char *) ptr );	/* see gtkdialog_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 579 "gtkdialog_lexer.l"



static gchar *
process_string(gchar *str)
{
	//fprintf(stderr, "%s(): Input = '%s'\n", __func__, str);
	// FIXME: Well, this will come tomorrow...
	return g_strdup(str);
}


