#!/bin/sh

GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<vbox>
  <vbox border-width="30">
    <text>
      <label>This is static text which will automatically wrap by default at some point.</label>
      <action signal="show">echo "The show signal was emitted - the only signal supported"</action>
    </text>
  </vbox>
  <hseparator></hseparator>
  <hbox homogeneous="true">
    <button ok></button>
  </hbox>
</vbox>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
